### ISSUE TITLE
Illegal Argument Exception

### ISSUE THREAD

**Issue by colinhercus** [PapenfussLab/gridss#108]
Hi,

I'm adding SA tags to Novoalign's output for use in GRIDSS and SV callers however I'm getting some strange exceptions that could be from SA tags. I can't see what's wrong with them and hope you can help.

Novoalign is working slightly differently to bwa mem in that it only hard clips for 3' low quality bases and adapter sequences. Chimera alignments are soft clipped not hard clipped.

I've attached a couple of examples.
[IllegalArgumentException.txt](https://github.com/PapenfussLab/gridss/files/1672413/IllegalArgumentException.txt)

Thanks, Colin

**Comment by colinhercus** [comment]
Hi,
I'm getting some error on older BAM files without the SA tag as in...
NS500102:222:XXXXXXXXX:1:12211:5629:9449	99	chr19	41840215	70	115M36H	=	41840330	154	AGGTTGCAGTGAGCCAAGATCGTGCCACTGCACTCCACCCAGGGCAACAGGGTGAGACTCTGTCTTGAAAAGAAAAGAAAAAAGAAAGAAAAGAAAAGAAAAAGTTGACAATGCC	AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE/EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEA	PG:Z:novoalign	AS:i:0	UQ:i:0	NM:i:0	MD:Z:115	PQ:i:307	SM:i:70	AM:i:0
NS500102:222:XXXXXXXXX:1:12211:5629:9449	147	chr19	41840330	70	59H53S39M	=	41840215	-154	TTTTTAAAAAAAAAAAAAAAATAAATAAAAAAAAATAAAAATTTTTAAATTGGTTTTTTTTTTTTTTTTTTTTTTGAGACAGAGTCTTGCTC	A/AEA//EA//EEE/EEAEEE//A////EA/AEE//</AE//EAA//AA/////EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAAAAA	PG:Z:novoalign	AS:i:307	UQ:i:307	NM:i:0	MD:Z:39	PQ:i:307	SM:i:0	AM:i:0
ERROR	2018-01-29 15:33:19	SingleReadEvidence	createEvidence(): Error processing NS500102:222:XXXXXXXXX:1:12211:5629:9449 from normal.bam. Ignoring read. This should not happen and may be caused by a internally inconsistent input file (e.g. SA tag does not match read alignment). Please raise an issue at https://github.com/PapenfussLab/gridss/issues and include this stack trace as well as offending SAM record.
java.lang.IllegalArgumentException
	at au.edu.wehi.idsv.SingleReadEvidence.<init>(SingleReadEvidence.java:132)
	at au.edu.wehi.idsv.SplitReadEvidence.<init>(SplitReadEvidence.java:34)
	at au.edu.wehi.idsv.SplitReadEvidence.create(SplitReadEvidence.java:81)
	at au.edu.wehi.idsv.SingleReadEvidence.createEvidence(SingleReadEvidence.java:38)
	at au.edu.wehi.idsv.DirectedEvidenceIterator.addToBuffer(DirectedEvidenceIterator.java:36)
	at au.edu.wehi.idsv.DirectedEvidenceIterator.ensureBuffer(DirectedEvidenceIterator.java:32)
	at au.edu.wehi.idsv.DirectedEvidenceIterator.hasNext(DirectedEvidenceIterator.java:47)
	at com.google.common.collect.Iterators$5.computeNext(Iterators.java:662)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at com.google.common.collect.Iterators$PeekingImpl.hasNext(Iterators.java:1182)
	at au.edu.wehi.idsv.util.WindowedSortingIterator.advanceUnderlying(WindowedSortingIterator.java:76)
	at au.edu.wehi.idsv.util.WindowedSortingIterator.computeNext(WindowedSortingIterator.java:62)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at au.edu.wehi.idsv.util.AutoClosingIterator.hasNext(AutoClosingIterator.java:48)
	at au.edu.wehi.idsv.util.AsyncBufferedIterator$ReaderRunnable.run(AsyncBufferedIterator.java:123)
	at java.lang.Thread.run(Thread.java:748)

**Comment by d-cameron** [comment]
They were ok, I was incorrectly making a bwa-style assumption that the primary alignment record would not be hard clipped. I've updated my record preprocessing logic to replace hard clips with sequence that cannot be determined from other records with Ns.

Thanks for reporting this. The fix will be in the next GRIDSS release.

**Comment by colinhercus** [comment]
Hi Daniel,

Thanks, that was very fast :)

Best Regards, Colin
