### ISSUE TITLE
Merge -Dreference_fasta and REFERENCE command line arguments.

### ISSUE THREAD

**Issue by Lcarey** [PapenfussLab/gridss#109]
Hi,
I'm trying to work directly with CRAM files but I get the following error, which I assume comes from picard and not gridss : 

`[Thu Feb 01 18:08:59 CET 2018] gridss.CallVariants done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=2022178816
Exception in thread "main" java.lang.IllegalStateException: A valid CRAM reference was not supplied and one cannot be acquired via the property settings reference_fasta or use_cram_ref_download
	at htsjdk.samtools.cram.ref.ReferenceSource.getDefaultCRAMReferenceSource(ReferenceSource.java:106)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:395)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:205)
	at gridss.cmdline.MultipleSamFileCommandLineProgram.ensureDictionariesMatch(MultipleSamFileCommandLineProgram.java:176)
	at gridss.cmdline.MultipleSamFileCommandLineProgram.doWork(MultipleSamFileCommandLineProgram.java:213)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:268)
	at gridss.CallVariants.main(CallVariants.java:109)
`

**Comment by d-cameron** [comment]
In theory it is supposed to work because the htsjdk library I use supports CRAM but I haven't actually tried it myself. The error message indicates that adding -Dreference_fasta=/path/to/your/fasta.fa to your command-line arguments should resolve this error (just make sure to add it before gridss.CallVariants so java interprets it correctly).

I'll look into getting the reference passed down to the SAM/BAM/CRAM loading code so you won't have 
to pass it on the command line twice if using CRAM.
