### ISSUE TITLE
Error at assembly stage

### ISSUE THREAD

**Issue by KeyTals** [PapenfussLab/gridss#110]
Hi,
I am running gridss to find somatic structure variation but gridss hangs or error out at specific chunk of the assembly.

INFO    2018-02-05 21:54:41     SAMFileUtil     Sorting ./NC_somatic.vcf.assembly.bam.gridss.working/gridss.tmp.NC_somatic.vcf.assembly.bam.assembly.chunk297.bam
Exception in thread "pool-10-thread-1" htsjdk.samtools.util.RuntimeIOException:./NC_somatic.vcf.assembly.bam.gridss.working/gridss.tmp.NC_somatic.vcf.assembly.bam.assembly.chunk297.bam has invalid uncompressedLength: -39542895
        at htsjdk.samtools.util.BlockCompressedInputStream.inflateBlock(BlockCompressedInputStream.java:543)
        at htsjdk.samtools.util.BlockCompressedInputStream.processNextBlock(BlockCompressedInputStream.java:532)
        at htsjdk.samtools.util.AsyncBlockCompressedInputStream$AsyncBlockCompressedInputStreamRunnable.run(AsyncBlockCompressedInputStream.java:225)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Could you please inform me how to avoid this error.

Thanks,
Keyur

**Comment by d-cameron** [comment]
>htsjdk.samtools.util.RuntimeIOException:./NC_somatic.vcf.assembly.bam.gridss.working/gridss.tmp.NC_somatic.vcf.assembly.bam.assembly.chunk297.bam has invalid uncompressedLength: -39542895

That looks very much like the file is corrupt. Did you run `gridss.CallVariants` with the -`Dgridss.gridss.output_to_temp_file=true` option?
