### ISSUE TITLE
GRIDSS 1.5.1 PositionalAssembler exception encountered during CallVariants

### ISSUE THREAD

**Issue by johnaach** [PapenfussLab/gridss#140]
I am trying to get GRIDSS CallVariants to run on a complete genome for which the BAM files were delivered one-per-chromosome.  My interpretation of your documentation is that this will require me to merge the BAM files together and present the merged BAM as a single INPUT to GRIDSS, and I have been testing this strategy with my chr21 and chr22 BAMs.  I earlier verified that GRIDSS would run to completion without incident on the chr22 BAM file alone. 

To create this merged test BAM INPUT file, I used Picard MergeSAMFiles to merge the two BAMs, and found that I needed to follow this up with a ReorderSam (with ALLOW_INCOMPLETE_DICT_CONCORDANCE=true) in order for GRIDSS to accept the merged INPUT.  I am finding that CallVariants gets through assembly of most of the "chunks" but runs into the following PositionalAssembler ERROR on one particular "chunk" (145):  

ERROR   2018-05-30 09:13:43     PositionalAssembler     Assembly recovery attempt failed due to exception thrown by underlying iterator
java.lang.IllegalStateException
        at com.google.common.base.Preconditions.checkState(Preconditions.java:485)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:132)
        at com.google.common.collect.Iterators$PeekingImpl.hasNext(Iterators.java:1182)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:95)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.hasNext(PositionalAssembler.java:56)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:228)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:183)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$14(AssemblyEvidenceSource.java:89)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Subsequent to this I get a second PositionalAssembler ERROR, and a follow-on message identifying the chunk:

ERROR   2018-05-30 09:13:43     PositionalAssembler     Assembly recovery attempt failed due to exception thrown by underlying iterator
java.lang.IllegalStateException
        at com.google.common.base.Preconditions.checkState(Preconditions.java:485)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:132)
        at com.google.common.collect.Iterators$PeekingImpl.hasNext(Iterators.java:1182)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:95)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.hasNext(PositionalAssembler.java:56)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:228)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:183)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$14(AssemblyEvidenceSource.java:89)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
INFO    2018-05-30 09:13:43     AssemblyEvidenceSource  Starting assembly on chunk 166 (chr2:206790020-chr2:216790019)
ERROR   2018-05-30 09:13:43     PositionalAssembler     Error assembling chr22. This should not happen. Please raise an issue at https://github.com/PapenfussLab/gridss/issues
... 
ERROR   2018-05-30 09:13:43     AssemblyEvidenceSource  Error assembling chunk 145 (chr22:48344586-chr2:6790019)

I have additionally determined the following:

(1) The problem is repeatable.  The messages above come from a second run, the first of which resulted in the same ERROR on the same chunk with the same chromosomal locations.  The first and second run differed in the order of the chunk processing messages (presumably due to asynchronous multi-threading of several chunk assembles concurrently).

(2) Unlike most of the chunk messages in the log, chunk 145 messages indicate that GRIDSS is attempting to assemble reads associated with two distinct chromosomes: chr22 and chr2.  However, inspection of the log indicates that inter-chromosomal assemblies were successfully completed for ~10 other chunks prior to encountering the chunk 145 error, so this does not seem to be a problem with inter-chromosomal assembly per se.

Any advice you can give me on getting past this problem would be much appreciated.  I am attaching the complete log and GRIDSS shell script for this run.  Note that the script is adapted to run GRIDSS under SLURM on our compute cluster.

Thanks very much for your attention,
--- John Aach

[run_gridss_chr21_22_test.05302018.15344907.out.txt](https://github.com/PapenfussLab/gridss/files/2054244/run_gridss_chr21_22_test.05302018.15344907.out.txt)
[run_gridss_chr21_22_test.05302018.txt](https://github.com/PapenfussLab/gridss/files/2054245/run_gridss_chr21_22_test.05302018.txt)

**Comment by d-cameron** [comment]
It looks like the reference genome that the reads were originally aligned to does not match the reference genome supplied to GRIDSS. GRIDSS is crashing when attempting to lookup up the length of a reference contig that does not exist. GRIDSS trusts the `SA` tag of reads and as the log file has a whole lot of error messages along the lines of:
```
WARNING	2018-05-30 09:02:58	SAMRecordUtil	SA tag of read E00504:58:H2MTWCCXY:1:1101:10236:34764 refers to missing alignments [chrUn_gl000225,196992,+,29S56M65S,5,0, chr4,49097595,-,31S56M63S,0,3]
```

it looks very much like you have a split read alignment to a contig (such as chrUn_gl000225) that does not exist in the hg19 reference you supplied to GRIDSS.

GRIDSS requires the reference genome supplied to GRIDSS to exactly match the reference genome supplied to the aligner.

**Comment by johnaach** [comment]
That was precisely the problem!  The version of hg19 at our installation differed from that used at the sequencing facility by not containing the unlocalized, random, and hap contigs.  I downloaded a full version of hg19, generated the corresponding BWA index, and regenerated my test-merged chr21 and chr22 BAM file.  GRIDSS ran without error with these versions of the files and generated a final SV VCF file.

Thanks very much for your help!
--- John Aach
