### ISSUE TITLE
Mate unmapped flag should not be set for unpaired read

### ISSUE THREAD

**Issue by fitbio** [PapenfussLab/gridss#145]
Hi,

I used the example_pipeline.sh from the gridds example folder for analysing my fastq files. Everything works fine till the point where I use "ExtractSVReads"  where it throws me out this error

ERROR   2018-06-13 08:56:01     CallVariants    Fatal exception thrown by worker thread.
htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Record 3, Read name HS6_6638:1:2108:6080:193688, Mate unmapped flag should not be set for unpaired read.
        at htsjdk.samtools.SAMUtils.processValidationErrors(SAMUtils.java:454)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:812)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:797)
        at htsjdk.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:765)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:576)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:548)
        at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:136)
        at picard.analysis.CollectMultipleMetrics.doWork(CollectMultipleMetrics.java:426)
        at gridss.analysis.CollectGridssMetrics.doWork(CollectGridssMetrics.java:68)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:282)
        at au.edu.wehi.idsv.SAMEvidenceSource.execute(SAMEvidenceSource.java:156)
        at au.edu.wehi.idsv.SAMEvidenceSource.ensureMetrics(SAMEvidenceSource.java:140)
        at gridss.CallVariants$1$1.call(CallVariants.java:55)
        at gridss.CallVariants$1$1.call(CallVariants.java:51)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

I have used the 1.7.1 version of gridds. Do I need to change any parameters in the workflow. I need help. Do I need to take any steps manually to correct this problem?

**Comment by d-cameron** [comment]
>I need help. Do I need to take any steps manually to correct this problem?

You need to fix your input file so it is a valid SAM/BAM file. Use picard tools ValidateSamFile to identify issues with your input file, correct them, then run GRIDSS on the corrected input file.

**Comment by fitbio** [comment]
Thank you very much for your quick reply. I used validate samFIle from picard for one the bam file .
It showed me these errors.
ERROR:INVALID_FLAG_FIRST_OF_PAIR        420140
ERROR:INVALID_FLAG_MATE_UNMAPPED        221429
ERROR:INVALID_FLAG_SECOND_OF_PAIR       179716
ERROR:MATE_NOT_FOUND    15839

Any suggestions how can I clear out these errors. I used the same parameters for bwa mem and samtools suggested from example_pipeline.sh file. 

Thank you in Advance.

**Comment by d-cameron** [comment]
I'm not sure what other steps or filtering you have done other that just `bwa mem -Y | samtool sort -` but clearly some additional processing has been done as I've never seen bwa output invalid read pairing flags. Running `samtools view -H` and looking at the `@PG` tags might help narrow down what program it was that you ran on your data that corrupted your flags.

If you're not sure at all, I recommend going back to the raw fastq files and starting again with a pipeline that only does adapter trimming, alignment, sorting, and duplicate marking.

**Comment by fitbio** [comment]
Thank you for your reply and for the suggestions.
I used ValidateSam fie from picard to analyse my bam file.
I got these errors.
ERROR:INVALID_FLAG_FIRST_OF_PAIR        314565
ERROR:INVALID_FLAG_MATE_UNMAPPED        136464
ERROR:INVALID_FLAG_SECOND_OF_PAIR       129593
ERROR:MATE_NOT_FOUND    30072

So I used samtools view -F 12 -q 0 to remove  unpaired reads after alignment with bwa-mem. Then followed by samtools fixmate, sort and rmdup. 

Then gridds workflow works just fine. I am getting the results. 

But from the gridss paper, I have seen it uses discordant read pairs information to infer breakpoints and also for split read alignment. 

My question is it safe to remove unpaired reads from bam file?
Thank you,
Kind Regards

**Comment by fitbio** [comment]
Also these are the kind of reads which i face the problem. But when I remove these gridss works just fine.



HWI-ST1212:66:D1C4LACXX:5:1308:12759:51912      64      chr1    899806  60      100M    *       0       0       GTACGTGGCAGGGGGCAACGACGGCACCAGCTGCCTCAACTCGGTAGAGAGATACAGTCCAAAGGCTGGAGCCTGGGAAAGCGTGGCGCCCATGAATATC    >?&><>BABCBBB@@BA?@<@@:ABA@@ABAAABAAA?>@BA;@<=>@AAA@>>@BB?BAB>AA?ACB?BBCCDC>A??DCD?7??<;C?D67;AC@=>B MC:Z:13M1I29M   BD:Z:LLNNRSPSSRRQNMMQOKLLMMLMOMHLLNNNMMNMJKIJLJLLMLMJLJLJLJLHNMLLMJBLNOONNMMOONNNKNLCMPNNLOQOOQNPPQQPLLLN       MD:Z:100        RG:Z:732    BI:Z:OOQOSSQQTRSQNNMQPLNNLONMPOLNNPQQONNOLNKMOLKMPOPNONOOPNMKQOQKOLFPOQRQNNQSQQRONONGRTQQPPTRSSPSSTUSNOPO        NM:i:0  AS:i:100        XS:i:0

**Comment by fitbio** [comment]
Thank you very much. I removed the read pairs in which both reads are unmapped (As listed in the gridss paper) using samtools view. It worked just fine.
