### ISSUE TITLE
AssemblyEvidenceSource  Error assembling chunk

### ISSUE THREAD

**Issue by sheenams** [PapenfussLab/gridss#162]
I'm running into this issue with 2 of my 8 samples (the other 6 work fine). 
```
ERROR   2018-08-15 16:38:41     AssemblyEvidenceSource  Error assembling chunk 12 (1:120000001-1:130000000)
java.lang.NullPointerException
        at au.edu.wehi.idsv.NonReferenceReadPair.meetsAnchorCriteria(NonReferenceReadPair.java:130)
        at au.edu.wehi.idsv.NonReferenceReadPair.create(NonReferenceReadPair.java:60)
        at au.edu.wehi.idsv.NonReferenceReadPair.create(NonReferenceReadPair.java:122)
        at au.edu.wehi.idsv.DirectedEvidenceIterator.addToBuffer(DirectedEvidenceIterator.java:38)
        at au.edu.wehi.idsv.DirectedEvidenceIterator.ensureBuffer(DirectedEvidenceIterator.java:32)
        at au.edu.wehi.idsv.DirectedEvidenceIterator.hasNext(DirectedEvidenceIterator.java:47)
        at com.google.common.collect.Iterators$5.computeNext(Iterators.java:662)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
        at com.google.common.collect.Iterators$PeekingImpl.hasNext(Iterators.java:1182)
        at au.edu.wehi.idsv.util.WindowedSortingIterator.advanceUnderlying(WindowedSortingIterator.java:76)
        at au.edu.wehi.idsv.util.WindowedSortingIterator.computeNext(WindowedSortingIterator.java:62)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
        at com.google.common.collect.Iterators$5.computeNext(Iterators.java:662)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
        at au.edu.wehi.idsv.util.AutoClosingIterator.hasNext(AutoClosingIterator.java:48)
        at au.edu.wehi.idsv.util.AutoClosingIterator.hasNext(AutoClosingIterator.java:48)
        at com.google.common.collect.Iterators$MergingIterator.<init>(Iterators.java:1322)
        at com.google.common.collect.Iterators.mergeSorted(Iterators.java:1291)
        at au.edu.wehi.idsv.util.AutoClosingMergedIterator.<init>(AutoClosingMergedIterator.java:48)
        at au.edu.wehi.idsv.SAMEvidenceSource.mergedIterator(SAMEvidenceSource.java:521)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:226)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:187)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$1(AssemblyEvidenceSource.java:93)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
ERROR   2018-08-15 16:38:41     AssemblyEvidenceSource  Error assembling chunk 20 (1:200000001-1:210000000)
java.lang.NullPointerException
```

I've seen this in a couple 'closed' issues, but their problem was a different reference genome being used in alignment. My reference genome is the same in both steps. I'm also seeing this warning in both of my failing samples (but not the other 6) (unsure if it is related):
```
INFO    2018-08-15 16:38:39     IdsvSamFileMetrics      No pair-end insert size metrics found in output/165R05_E01_MONCv1_MA0337/165R05_E01_MONCv1_MA0337.final.bam.gridss.working/165R05_E01_MONCv1_MA0337.final.bam.insert_size_metrics. Assuming this library contains single-end reads
```
Is there some pre-processing of these 2 samples that I need to do to make it work?

**Comment by d-cameron** [comment]
> unsure if it is related

The error is caused by an attempt to look up the metrics file which does not exist.

> Is there some pre-processing of these 2 samples that I need to do to make it work?

If they are indeed paired end, then you'll need to work out why picard CollectInsertSizeMetrics is failing. Try running the stand-alone picard version and see if that throws any errors. If that works, please check the full log file to see if there was any error during the early CollectGridssMetrics step that would indicate why the insert size metrics file never got written.

If they're single-end reads then you'll need fix your SAM flags because some of your reads have their paired flag set.
