### ISSUE TITLE
Fatal error during assembly

### ISSUE THREAD

**Issue by kstaderm** [PapenfussLab/gridss#208]
Hello!
I ran gridss on a larger set of samples. For most of the samples gridss finished without a problem but for some of the samples I keep running into errors, re-running the samples did not help. The log file contains hundreds of errors that look like the following one:

`ERROR	2019-04-09 11:58:38	SupportNodeIterator	Error: kmer in evidence ShPAATxFXSatGNnrGcFcCUN4W92a-DTL of read NS500286:273:HN3THBGX9:1:22105:10475:16293 (chr6:31575163 123M27S) out of bounds. Kmer support starts at 31575056 which is more than 222 before the breakpoint start position at (5):31575293(31575285-31575302)> (2):109558937(109558929-109558946)>
`

For each Chromosome in my reference I get the following error multiple timer:
`ERROR	2019-04-09 11:58:38	PositionalAssembler	Error assembling chr6. This should not happen. Please raise an issue at https://github.com/PapenfussLab/gridss/issues. Attempting recovery by resuming assembly at chr6:31849119
java.lang.AssertionError
	at au.edu.wehi.idsv.debruijn.positional.KmerPathNode.removeWeight(KmerPathNode.java:961)
	at au.edu.wehi.idsv.debruijn.positional.KmerPathNode.removeWeight(KmerPathNode.java:902)
	at au.edu.wehi.idsv.debruijn.positional.KmerPathNode.removeWeight(KmerPathNode.java:839)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.removeWeight(NonReferenceContigAssembler.java:733)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.removeFromGraph(NonReferenceContigAssembler.java:631)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.callContig(NonReferenceContigAssembler.java:555)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.flushCallsOutsideRetainWindow(NonReferenceContigAssembler.java:198)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.ensureCalledContig(NonReferenceContigAssembler.java:225)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.hasNext(NonReferenceContigAssembler.java:162)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.flushIfRequired(PositionalAssembler.java:70)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:110)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:86)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.hasNext(PositionalAssembler.java:56)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:228)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:188)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$1(AssemblyEvidenceSource.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

Finally, gridss stops with the following error message:
`INFO	2019-04-09 11:59:35	AssemblyEvidenceSource	Breakend assembly complete.
ERROR	2019-04-09 11:59:35	AssemblyEvidenceSource	Fatal error during assembly 
java.util.concurrent.ExecutionException: java.lang.AssertionError
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.runTasks(AssemblyEvidenceSource.java:155)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleBreakends(AssemblyEvidenceSource.java:93)
	at gridss.CallVariants.doWork(CallVariants.java:127)
	at gridss.cmdline.MultipleSamFileCommandLineProgram.doWork(MultipleSamFileCommandLineProgram.java:195)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
	at gridss.CallVariants.main(CallVariants.java:109)
Caused by: java.lang.AssertionError
	at au.edu.wehi.idsv.debruijn.positional.KmerPathNode.removeWeight(KmerPathNode.java:961)
	at au.edu.wehi.idsv.debruijn.positional.KmerPathNode.removeWeight(KmerPathNode.java:934)
	at au.edu.wehi.idsv.debruijn.positional.KmerPathNode.removeWeight(KmerPathNode.java:839)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.removeWeight(NonReferenceContigAssembler.java:733)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.removeFromGraph(NonReferenceContigAssembler.java:631)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.callContig(NonReferenceContigAssembler.java:555)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.flushCallsOutsideRetainWindow(NonReferenceContigAssembler.java:198)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.ensureCalledContig(NonReferenceContigAssembler.java:225)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.hasNext(NonReferenceContigAssembler.java:162)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.flushIfRequired(PositionalAssembler.java:70)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:114)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:106)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.hasNext(PositionalAssembler.java:56)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:228)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:188)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$1(AssemblyEvidenceSource.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[Tue Apr 09 11:59:35 CEST 2019] gridss.CallVariants done. Elapsed time: 31.45 minutes.
Runtime.totalMemory()=23046651904
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.AssertionError
	at au.edu.wehi.idsv.AssemblyEvidenceSource.runTasks(AssemblyEvidenceSource.java:165)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleBreakends(AssemblyEvidenceSource.java:93)
	at gridss.CallVariants.doWork(CallVariants.java:127)
	at gridss.cmdline.MultipleSamFileCommandLineProgram.doWork(MultipleSamFileCommandLineProgram.java:195)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
	at gridss.CallVariants.main(CallVariants.java:109)
Caused by: java.util.concurrent.ExecutionException: java.lang.AssertionError
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.runTasks(AssemblyEvidenceSource.java:155)
	... 5 more
Caused by: java.lang.AssertionError
	at au.edu.wehi.idsv.debruijn.positional.KmerPathNode.removeWeight(KmerPathNode.java:961)
	at au.edu.wehi.idsv.debruijn.positional.KmerPathNode.removeWeight(KmerPathNode.java:934)
	at au.edu.wehi.idsv.debruijn.positional.KmerPathNode.removeWeight(KmerPathNode.java:839)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.removeWeight(NonReferenceContigAssembler.java:733)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.removeFromGraph(NonReferenceContigAssembler.java:631)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.callContig(NonReferenceContigAssembler.java:555)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.flushCallsOutsideRetainWindow(NonReferenceContigAssembler.java:198)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.ensureCalledContig(NonReferenceContigAssembler.java:225)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.hasNext(NonReferenceContigAssembler.java:162)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.flushIfRequired(PositionalAssembler.java:70)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:114)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:106)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.hasNext(PositionalAssembler.java:56)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:228)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:188)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$1(AssemblyEvidenceSource.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

I am using version 2.2.2 and bwa as mapper, gridss is using 16 threads and I tried 31 and 60 GB memory, the gridss call is looking like this:
`java -ea -Xmx60g -Dreference_fasta=${REFERENCE} -Dsamjdk.create_index=true -Dsamjdk.use_async_io_read_samtools=true -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=true -Dsamjdk.buffer_size=4194304 -Dgridss.gridss.output_to_temp_file=true -cp $GRIDSS_JAR gridss.CallVariants WORKER_THREADS=16 TMP_DIR=. WORKING_DIR=. REFERENCE_SEQUENCE=${REFERENCE} INPUT=${OUT_BASE}.sorted.bam OUTPUT=${OUTPUT} ASSEMBLY=${ASSEMBLY} BLACKLIST=${BLACKLIST}
`

Thank you in advance for your help!

Kind regards,
Kai

**Comment by kstaderm** [comment]
Thank you in advance for your help!

Kind regards,
Kai

**Comment by d-cameron** [comment]
It appears there is an issue with some of the reads in your input data. Are you able to post the read alignments for the offending read (`samtools view YOURFILE.bam chr6:31500000-31600000 | grep "NS500286:273:HN3THBGX9:1:22105:10475:16293"`)? For some reason, the assembler thinks you have read kmers that start before the read itself.

**Comment by kstaderm** [comment]
Unfortunately, I can not provide any data from the problematic data-set. But thanks for pointing me in the direction of the read alignment! I adjusted read trimming and mapping (now using bowtie2) and a lot of samples that did not process before now finished successfully. However, for few samples the error still exists.
