### ISSUE TITLE
Error assembly chr*. This should not happen.

### ISSUE THREAD

**Issue by cboursnell** [PapenfussLab/gridss#224]
I got this error 631 times from running on 2 bam files (tumour-normal pair)
`ERROR   2019-07-02 14:11:18     PositionalAssembler     Error assembling chr1. This should not happen. Please raise an issue at https://github.com/PapenfussLab/gridss/issues. Attempting recovery by resuming assembly at chr1:30422723
au.edu.wehi.idsv.SanityCheckFailureException: Subnode [30405501-30405518][30405492-30405518]  1323w ATCCCTTGCCACCTGAGACCAAAA GAAGGAAAAAAAAACTGCTTATTCTGTAGCTTCATGTCCTCTCTGGTCCCGACCCCCAGCAG (63)  reachable from score=105 pathlength=5 [30405496-30405513][30405496-30405513]  105w ATATCCCTTGCCACCTGAGAC CAAA (5)  not memoized. [629 nodes memoized, 2 in frontier, maxVisitedEndPosition=30414885, nextPosition=30415054]
        at au.edu.wehi.idsv.debruijn.positional.MemoizedContigCaller.visit(MemoizedContigCaller.java:205)
        at au.edu.wehi.idsv.debruijn.positional.MemoizedContigCaller.advanceFrontier(MemoizedContigCaller.java:183)
        at au.edu.wehi.idsv.debruijn.positional.MemoizedContigCaller.callBestContigStartingBefore(MemoizedContigCaller.java:335)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.flushCallsOutsideRetainWindow(NonReferenceContigAssembler.java:188)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.ensureCalledContig(NonReferenceContigAssembler.java:223)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.hasNext(NonReferenceContigAssembler.java:160)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.flushIfRequired(PositionalAssembler.java:64)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:104)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:80)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.hasNext(PositionalAssembler.java:50)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:224)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:183)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$1(AssemblyEvidenceSource.java:86)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
ERROR   2019-07-02 14:11:23     NonReferenceContigAssembler     Sanity check failure: found path with no support. Attempting to recover by direct node removal chr1
`

I am running gridss-2.4.0-gridss-jar-with-dependencies.jar gridss.CallVariants

**Comment by d-cameron** [comment]
Is there any chance you would be able to supply either the full bams or (preferably) a small region of the bam that can reproduce the error?

If not, can you confirm that your BAM are internally consistent. In particular:

- Read names are unique (this is the most likely culprit. Multiple records with the same read name will cause serious issues with the GRIDSS assembly)
- SAM flags are consistent
- mate fields actually match the SAMRecord for the mate
