### ISSUE TITLE
htsjdk.samtools.SAMFormatException

### ISSUE THREAD

**Issue by davisem** [PapenfussLab/gridss#236]
Hi. I encountered the following error while running your program. 
```
ERROR	2019-08-14 17:19:22	CallVariants	Fatal exception thrown by worker thread.
htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Record 967938534, Read name HWI-ST729:215:D2FLHACXX:4:1112:6147:62475, MAPQ should be 0 for unmapped read.
	at htsjdk.samtools.SAMUtils.processValidationErrors(SAMUtils.java:446)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.decode(BAMFileReader.java:868)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator.access$1900(BAMFileReader.java:777)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator$AsyncBamDecoder.transform(BAMFileReader.java:916)
	at htsjdk.samtools.BAMFileReader$BAMFileIterator$AsyncBamDecoder.transform(BAMFileReader.java:899)
	at htsjdk.samtools.util.AsyncReadTaskRunner.processNextBatch(AsyncReadTaskRunner.java:228)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

The bam spec states:

"Bit 0x4 is the only reliable place to tell whether the read is unmapped. If 0x4 is set, no assumptions can be made about RNAME, POS, CIGAR, MAPQ, and bits 0x2, 0x100, and 0x800."

I realize that this is an htsjdk issue. But would it be possible to suppress this error internally? 

Thanks.

**Comment by d-cameron** [comment]
Try adding `VALIDATION_STRINGENCY=LENIENT` or `VALIDATION_STRINGENCY=SILENT` to the command line.

**Comment by davisem** [comment]
Thanks, setting the stringency to lenient did the trick.
