### ISSUE TITLE
PositionalAssembler  Error

### ISSUE THREAD

**Issue by Griffan** [PapenfussLab/gridss#237]
Gridss says:
```
ERROR   2019-08-19 11:54:29     PositionalAssembler     Error assembling 2. This should not happen. Please raise an issue at https://github.com/PapenfussLab/gridss/issues. Attempting recovery by resuming assembly at 2:33112102
au.edu.wehi.idsv.SanityCheckFailureException: Subnode [33091928-33092897][33091926-33092897]  723w AGCACTTTGGGAGGCCGAGGCAGGT GGATCACCTGAGGTCAGGAGT (22)  reachable from score=175 pathlength=5 [33091923-33092892][33091923-33092892]  175w ATCCCAGCACTTTGGGAGGCCGAGG CAGG (5)  not memoized. [472 nodes memoized, 2 in frontier, maxVisitedEndPosition=33099399, nextPosition=33099510]
at au.edu.wehi.idsv.debruijn.positional.MemoizedContigCaller.visit(MemoizedContigCaller.java:205)
        at au.edu.wehi.idsv.debruijn.positional.MemoizedContigCaller.advanceFrontier(MemoizedContigCaller.java:183)
        at au.edu.wehi.idsv.debruijn.positional.MemoizedContigCaller.callBestContigStartingBefore(MemoizedContigCaller.java:335)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.flushCallsOutsideRetainWindow(NonReferenceContigAssembler.java:197)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.ensureCalledContig(NonReferenceContigAssembler.java:232)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.hasNext(NonReferenceContigAssembler.java:169)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.flushIfRequired(PositionalAssembler.java:69)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:109)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:85)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.hasNext(PositionalAssembler.java:55)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:220)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:178)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$1(AssemblyEvidenceSource.java:87)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

In total, I have encountered 13 this kind of errors.

**Comment by d-cameron** [comment]
Should be resolved in 2.6.2
