### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by davisem** [PapenfussLab/gridss#239]
```
ERROR	2019-08-22 10:32:58	AssemblyEvidenceSource	Error assembling chunk 22 (1:220000001-1:230000000)
java.lang.NullPointerException
	at au.edu.wehi.idsv.DirectedEvidenceIterator.addToBuffer(DirectedEvidenceIterator.java:42)
	at au.edu.wehi.idsv.DirectedEvidenceIterator.ensureBuffer(DirectedEvidenceIterator.java:31)
	at au.edu.wehi.idsv.DirectedEvidenceIterator.hasNext(DirectedEvidenceIterator.java:53)
	at com.google.common.collect.Iterators$5.computeNext(Iterators.java:662)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at com.google.common.collect.Iterators$5.computeNext(Iterators.java:662)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at au.edu.wehi.idsv.util.AutoClosingIterator.hasNext(AutoClosingIterator.java:47)
	at au.edu.wehi.idsv.util.AutoClosingIterator.hasNext(AutoClosingIterator.java:47)
	at com.google.common.collect.Iterators$MergingIterator.<init>(Iterators.java:1322)
	at com.google.common.collect.Iterators.mergeSorted(Iterators.java:1291)
	at au.edu.wehi.idsv.util.AutoClosingMergedIterator.<init>(AutoClosingMergedIterator.java:47)
	at au.edu.wehi.idsv.SAMEvidenceSource.mergedIterator(SAMEvidenceSource.java:573)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:214)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:178)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$19(AssemblyEvidenceSource.java:87)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by d-cameron** [comment]
Should be resolved in 2.6.2
