### ISSUE TITLE
Out of memory crash

### ISSUE THREAD

**Issue by d-cameron** [PapenfussLab/gridss#247]
GRIDSS log when crashing:
```
•	INFO 2019-09-18 21:08:41 TwoBitBufferedReferenceSequenceFile Caching reference genome contig GL000209.1
•	WARNING 2019-09-18 21:25:13 AsyncBufferedIterator Thread interrupt received whilst closing underlying iterator
•	[Wed Sep 18 21:25:14 UTC 2019] gridss.SoftClipsToSplitReads done. Elapsed time: 24.48 minutes.
•	Runtime.totalMemory()=4589092864
•	Exception in thread "main" java.lang.IllegalArgumentException: Self-suppression not permitted
•	at java.lang.Throwable.addSuppressed(Throwable.java:1043)
•	at au.edu.wehi.idsv.SplitReadRealigner.mergeSupplementaryAlignment(SplitReadRealigner.java:335)
•	at au.edu.wehi.idsv.SplitReadRealigner.createSupplementaryAlignments(SplitReadRealigner.java:303)
•	at gridss.SoftClipsToSplitReads.doWork(SoftClipsToSplitReads.java:90)
•	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
•	at gridss.SoftClipsToSplitReads.main(SoftClipsToSplitReads.java:110)
•	Caused by: java.lang.OutOfMemoryError: Java heap space
•	Running GRIDSS filter step.

```

**Comment by d-cameron** [comment]
Out of memory due to the -Xmx4GB and MAX_RECORDS_IN_RAM=500000 not allocating enough to perform the in-memory sorting step.
