### ISSUE TITLE
Error assembling

### ISSUE THREAD

**Issue by YuanwenGuo** [PapenfussLab/gridss#262]
Hi,
I was trying to call SVs for ~70 samples with GRIDSS 2.6.2, and got error message about PositionalAssembler multiple times. Please see the following few lines at the end of log file:
ERROR	2019-09-26 12:27:44	PositionalAssembler	Error assembling scaffold_4. Please raise an issue at https://github.com/PapenfussLab/gridss/issues
au.edu.wehi.idsv.SanityCheckFailureException: Subnode [2289572-2289579][2289565-2289643]  609w GGCGACTTTCTGATATTGAGACTTT GTTTCCTCCTGTTGAGGTGGACCAGGTG (29)  reachable from score=168 pathlength=8 [2289567-2289574][2289567-2289574]  105w GGTGGGCGACTTTCTGATATTGAG ACTT (5) [2289564-2289571][2289564-2289571]  63w AGGTGGTGGGCGACTTTCTGATATT GA (3)  not memoized. [1458 nodes memoized, 43 in frontier, maxVisitedEndPosition=2296843, nextPosition=2296845]
	at au.edu.wehi.idsv.debruijn.positional.MemoizedContigCaller.visit(MemoizedContigCaller.java:205)
	at au.edu.wehi.idsv.debruijn.positional.MemoizedContigCaller.advanceFrontier(MemoizedContigCaller.java:183)
	at au.edu.wehi.idsv.debruijn.positional.MemoizedContigCaller.callBestContigStartingBefore(MemoizedContigCaller.java:335)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.flushCallsOutsideRetainWindow(NonReferenceContigAssembler.java:200)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.ensureCalledContig(NonReferenceContigAssembler.java:238)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.hasNext(NonReferenceContigAssembler.java:172)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.flushIfRequired(PositionalAssembler.java:73)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:137)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:100)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:128)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.hasNext(PositionalAssembler.java:58)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:220)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:178)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$1(AssemblyEvidenceSource.java:87)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
ERROR	2019-09-26 12:27:44	AssemblyEvidenceSource	Error assembling chunk 3 (scaffold_4:2278914-scaffold_6:1971746)
au.edu.wehi.idsv.SanityCheckFailureException: Subnode [2289572-2289579][2289565-2289643]  609w GGCGACTTTCTGATATTGAGACTTT GTTTCCTCCTGTTGAGGTGGACCAGGTG (29)  reachable from score=168 pathlength=8 [2289567-2289574][2289567-2289574]  105w GGTGGGCGACTTTCTGATATTGAG ACTT (5) [2289564-2289571][2289564-2289571]  63w AGGTGGTGGGCGACTTTCTGATATT GA (3)  not memoized. [1458 nodes memoized, 43 in frontier, maxVisitedEndPosition=2296843, nextPosition=2296845]
	at au.edu.wehi.idsv.debruijn.positional.MemoizedContigCaller.visit(MemoizedContigCaller.java:205)
	at au.edu.wehi.idsv.debruijn.positional.MemoizedContigCaller.advanceFrontier(MemoizedContigCaller.java:183)
	at au.edu.wehi.idsv.debruijn.positional.MemoizedContigCaller.callBestContigStartingBefore(MemoizedContigCaller.java:335)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.flushCallsOutsideRetainWindow(NonReferenceContigAssembler.java:200)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.ensureCalledContig(NonReferenceContigAssembler.java:238)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.hasNext(NonReferenceContigAssembler.java:172)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.flushIfRequired(PositionalAssembler.java:73)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:137)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:100)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:128)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.hasNext(PositionalAssembler.java:58)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:220)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:178)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$1(AssemblyEvidenceSource.java:87)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Right now I am trying to do batch calling, and hopefully that can help to bypass this issue.

Thank you,
Yuanwen

**Comment by d-cameron** [comment]
Can you rerun with the latest version (https://github.com/PapenfussLab/gridss/releases/tag/v2.6.3)?
I found an assembly issue but I don't think it's related to this failure.  The key feature in the new version is that when an assembly error occurs, GRIDSS creates a minimal zip file containing only the reads in the assembly graph at the time of failure. This should greatly assist in debugging these rare assembly failures as once I can actually reproduce them locally, fixing them is usually very straight-forward.
