### ISSUE TITLE
gridss.GeneratePonBedpe failing on loading genotypes

### ISSUE THREAD

**Issue by ameynert** [PapenfussLab/gridss#293]
I'm attempting to run this on a set of GRIDSS 2.7.3 generated VCFs aligned to hg38. I get this error:

```
Exception in thread "main" java.lang.RuntimeException: Missing normal ordinal for 
        at gridss.GeneratePonBedpe.passesNormalFilter(GeneratePonBedpe.java:167)
        at gridss.GeneratePonBedpe.getBreakendSummary(GeneratePonBedpe.java:155)
        at gridss.GeneratePonBedpe.lambda$getFilteredIterator$3(GeneratePonBedpe.java:145)
        at com.google.common.collect.Iterators$6.transform(Iterators.java:820)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
        at com.google.common.collect.Iterators$5.computeNext(Iterators.java:663)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
        at com.google.common.collect.Iterators$PeekingImpl.hasNext(Iterators.java:1182)
        at au.edu.wehi.idsv.util.WindowedSortingIterator.advanceUnderlying(WindowedSortingIterator.java:71)
        at au.edu.wehi.idsv.util.WindowedSortingIterator.computeNext(WindowedSortingIterator.java:57)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
        at au.edu.wehi.idsv.util.AutoClosingIterator.hasNext(AutoClosingIterator.java:47)
        at com.google.common.collect.Iterators$MergingIterator.<init>(Iterators.java:1322)
        at com.google.common.collect.Iterators.mergeSorted(Iterators.java:1291)
        at gridss.GeneratePonBedpe.lambda$filteredMerge$1(GeneratePonBedpe.java:136)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1612)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at gridss.GeneratePonBedpe.filteredMerge(GeneratePonBedpe.java:138)
        at gridss.GeneratePonBedpe.doWork(GeneratePonBedpe.java:81)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
        at gridss.GeneratePonBedpe.main(GeneratePonBedpe.java:174)
```

The Genotype object being returned is coming back as null.

**Comment by ameynert** [comment]
Attached are the first 10 PASS variants from one of the VCFs.
[example.txt](https://github.com/PapenfussLab/gridss/files/4127972/example.txt)

**Comment by d-cameron** [comment]
Explicitly set the normal ordinal. Since you only have 1 sample, you can do this by adding `NORMAL_ORDINAL=0` to the command line.
