### ISSUE TITLE
continued unexpected stop

### ISSUE THREAD

**Issue by SJ-Kang** [PapenfussLab/gridss#300]
Hi, Dr. Cameron
I'm one of @helloeoh001's colleagues.

I analyzed clinical samples (including shared data) using latest version (v2.8.0) of GRIDSS.

I classified our samples into three cases according to whether the analysis is finished or not with v2.7.3 and v2.8.0.

case 1)
Some samples that finished analysis using v2.7.3 stopped when using v2.8.0
(millions of 'SupportNodeIterator' error occurred in v2.7.3 but analysis finished)

case 2)
Some samples that stopped when using v2.7.3 still stop in v2.8.0
(It stops with 'SupportNodeIterator' error followed by 'AssemblyEvidenceSource' errors)

case 3)
Some samples that stopped when using v2.7.3 now works in v2.8.0, but still occur many 'SupportNodeIterator' errors..

The examples of 'SupportNodeIterator' and 'AssemblyEvidenceSource' errors are as below

ERROR 2020-02-18 10:06:31 SupportNodeIterator Error: kmer in evidence Fb1n5YEjbC5HlNI8-IZ70OQcmtrLAgI- of read M03987:134:000000000-
BW6T7:1:2102:13960:7795 (chr1:184016819 102S44M) out of bounds. Kmer support starts at 184016636 which is more than 223 before the breakpoint
start position at (1):184016900(184016862-184016938)>

...

ERROR 2020-02-18 10:14:11 SupportNodeIterator Error: kmer in evidence F64YnuP4u7_v7JMdhsxFwAwhvA1Qg0A7 of read M03987:134:000000000-BW6T7:1:2105:6025:10691 (chr7:140422891 105M) out of bounds. Kmer support starts at 140422771 which is more than 223 before the breakpoint start position at (7):140423010(140422995-140423026)> (5):55360649(55360634-55360665)>
ERROR 2020-02-18 10:14:11 AssemblyEvidenceSource Error assembling chunk 156 (chr9:18573718-chr9:28573717)
java.lang.RuntimeException: Sanity check failure: found path with no support (chr9:22006042)
at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.callContig(NonReferenceContigAssembler.java:616)
at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.flushCallsOutsideRetainWindow(NonReferenceContigAssembler.java:208)
at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.ensureCalledContig(NonReferenceContigAssembler.java:238)
at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.hasNext(NonReferenceContigAssembler.java:172)
at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.flushIfRequired(PositionalAssembler.java:83)
at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:245)
at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:110)
at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:147)
at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:118)
at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.hasNext(PositionalAssembler.java:68)
at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:240)
at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:198)
at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$2(AssemblyEvidenceSource.java:100)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

It will be really thankful to solve this problem.
I attach bam and *minimal_reproduction_data_for_error_1.zip files about all three cases from gridss v2.8.0.

https://drive.google.com/open?id=1HHtqJaDf_s-j09HUL9GV78I5BMmjn-sh

Thank you for your helps and effort to solve our problems...

**Comment by d-cameron** [comment]
Sorry for the delay in getting to this. Repo data is great as it means I should be able to finally fix the intermittent assembly failures. I've requested access to the file.

**Comment by d-cameron** [comment]
Should be fixed in 2.8.1. Please reopen if this is not the case.
