### ISSUE TITLE
PositionalAssembler Error

### ISSUE THREAD

**Issue by larsmew** [PapenfussLab/gridss#308]
Hi,

I am using version 2.8.0 installed through conda. 4 out of my 5 samples completes successfully but the last one seem stuck. In the log the following lines keep repeating every 5-10 seconds:

```
WARNING 2020-03-09 02:09:17     PositionalAssembler     Error during assembly of chromosome chr3 (633 reads in graph). Attempting recovery by rebuilding assembly graph.

au.edu.wehi.idsv.SanityCheckFailureException: Traversal of kmer length 5405 ending at [195785628,195785629] contains an invalid subnode over [195783677-195783678].
        at au.edu.wehi.idsv.debruijn.positional.TraversalNode.checkValid(TraversalNode.java:139)
        at au.edu.wehi.idsv.debruijn.positional.TraversalNode.toSubnodeNextPath(TraversalNode.java:112)
        at au.edu.wehi.idsv.debruijn.positional.MemoizedContigCaller.asUnanchoredPath(MemoizedContigCaller.java:310)
        at au.edu.wehi.idsv.debruijn.positional.MemoizedContigCaller.frontierPath(MemoizedContigCaller.java:369)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.removeMisassembledPartialContig(NonReferenceContigAssembler.java:305)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.ensureCalledContig(NonReferenceContigAssembler.java:236)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.hasNext(NonReferenceContigAssembler.java:172)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.flushIfRequired(PositionalAssembler.java:83)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:240)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:110)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.hasNext(PositionalAssembler.java:68)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:240)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:198)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$2(AssemblyEvidenceSource.java:100)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748
```

I don't get a gridss_minimal_reproduction_data_for_error_1.zip.error_package directory for the failling sample only for the ones that have completed.

Any idea on how to fix this? 
Thanks.

**Comment by d-cameron** [comment]
> I don't get a gridss_minimal_reproduction_data_for_error_1.zip.error_package directory for the failling sample only for the ones that have completed.

If you have a debugging repo zip file generated, then that indicates a processing error and GRIDSS should have terminated. At the very least, you'll be missing assembly contigs for up to 10Mb after the location that the error occured in. Could you send through one of your repo zips? (email cameron.d wehi.edu.au if it's not public data).

There's a fix (4f1aee7) for a similar issue in GRIDSS 2.8.1 (currently undergoing full-size WGS regression testing prior to release) and this may be a symptom of the same underlying cause.

**Comment by d-cameron** [comment]
> the following lines keep repeating every 5-10 seconds

Are the positions the same, or is it a different each time? That particular error is due to the assembly detecting an invalid internal state. When this happens, the assembly graph gets flushed and reloaded. It's only if this recovery process fails that a debugging zip is created.

**Comment by larsmew** [comment]
Thanks for the quick reply!

I only see two working directories (one for each sample being analyzed) containing the metrics file and a folder containing lots of chunks of the assembly bam files. Other than that I have two log files (full and timing) and a libsswjni.so file. Wouldn't I expect to find the repo zips in the working directory?

It's the same error message each time with the 633 reads in the graph. How long is this process expected to continue? My jobs time out after 24 hours and it did not "fail" within that time frame - I guess that is why I am not seeing the debugging zip?

I can wait for version 2.8.1 to see if that fixes the issue.

**Comment by d-cameron** [comment]
2.8.1 released. Please reopen if this doesn't fix it.
