### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError error caused when running through docker on ec2 instance

### ISSUE THREAD

**Issue by alexiswl** [PapenfussLab/gridss#326]
Hello, having an issue running the gridss docker file on an ec2 instance. 
I've provided the commands used and error traceback of the issue.
I've also shown other errors found in the gridss log file.
I first obtained the issue running the gridss-purple-linx docker container.  I have copied the command used in the wrapper and run this on the gridss container and also obtained the same issue.
Any help would be greatly appreciated.

## Commands

Docker image ID:
```
$docker images | grep 'gridss/gridss'
gridss/gridss                                                          latest              772b52dde6fd        6 days ago          1.92GB
```

Docker command:
```
docker run \
  --ulimit nofile=100000:100000 \
  --volume /data/samples/SBJ_seqcii_020:/mnt/inputs:ro \
  --volume /data/refdata/hg19:/mnt/refdata:ro \
  --volume /data/sample_outputs_gridss_only/SBJ_seqcii_020:/mnt/outputs \
  --entrypoint /opt/gridss/gridss.sh \
  --env GRIDSS_JAR=/opt/gridss/gridss-2.8.3-gridss-jar-with-dependencies.jar \
  gridss/gridss:latest \
    -b /mnt/refdata/dbs/gridss/ENCFF001TDO.bed \
    -r /mnt/refdata/refgenomes/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.fasta \
    -o /mnt/outputs/gridss/SBJ_seqcii_020.gridss.vcf.gz \
    -a /mnt/outputs/gridss/SBJ_seqcii_020.assembly.bam \
    -w /mnt/outputs/gridss \
    -j /opt/gridss/gridss-2.8.3-gridss-jar-with-dependencies.jar \
    -t 16 \
    --jvmheap 60g \
    --labels SBJ_seqcii_020_N,SBJ_seqcii_020_T \
    --steps all \
    /mnt/inputs/SBJ_seqcii_020.bam /mnt/inputs/SBJ_seqcii_020_tumor.bam
```

Docker version:
```
$ docker --version
Docker version 19.03.6-ce, build 369ce74
```

Amazon OS version:
```
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

## Traceback

Full error traceback:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /mnt/outputs/gridss/snappy-1.1.7-320ed890-b076-4661-a611-bce803552483-libsnappyjava.so: /mnt/outputs/gridss/snappy-1.1.7-320ed890-b076-4661-a611-bce803552483-libsnappyjava.so: failed to map segment from shared object
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1946)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1828)
        at java.lang.Runtime.load0(Runtime.java:810)
        at java.lang.System.load(System.java:1088)
        at org.xerial.snappy.SnappyLoader.loadNativeLibrary(SnappyLoader.java:179)
        at org.xerial.snappy.SnappyLoader.loadSnappyApi(SnappyLoader.java:154)
        at org.xerial.snappy.Snappy.<clinit>(Snappy.java:47)
        at org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:99)
        at org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:91)
        at org.xerial.snappy.SnappyOutputStream.<init>(SnappyOutputStream.java:81)
        at htsjdk.samtools.util.SnappyLoader.<init>(SnappyLoader.java:58)
        at htsjdk.samtools.util.SnappyLoader.<init>(SnappyLoader.java:48)
        at htsjdk.samtools.util.TempStreamFactory.getSnappyLoader(TempStreamFactory.java:42)
        at htsjdk.samtools.util.TempStreamFactory.wrapTempOutputStream(TempStreamFactory.java:74)
        at htsjdk.samtools.util.SortingCollection.spillToDisk(SortingCollection.java:251)
        at htsjdk.samtools.util.SortingCollection.add(SortingCollection.java:182)
        at au.edu.wehi.idsv.vcf.VcfFileUtil$SortCallable.call(VcfFileUtil.java:99)
        at au.edu.wehi.idsv.vcf.VcfFileUtil.sort(VcfFileUtil.java:46)
        at au.edu.wehi.idsv.VariantCaller.callBreakends(VariantCaller.java:63)
        at gridss.IdentifyVariants.doWork(IdentifyVariants.java:32)
        at gridss.cmdline.MultipleSamFileCommandLineProgram.doWork(MultipleSamFileCommandLineProgram.java:190)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at gridss.IdentifyVariants.main(IdentifyVariants.java:26)
```

## Additional log errors;
```
$ grep ERROR gridss.full.*.1.log 
ERROR	2020-04-09 09:59:43	AlignerFactory	Unable to use sswjni library - inexact homology annotation will be very slow. Please ensure libsswjni for your OS and architecture can be found on java.library.path
ERROR	2020-04-09 12:13:21	AlignerFactory	Unable to use sswjni library - inexact homology annotation will be very slow. Please ensure libsswjni for your OS and architecture can be found on java.library.path
```

## Additional log warnings:
Warnings have been trimmed to appear only once.
```
08:08:17.979 WARN  NativeLibraryLoader - Unable to load libgkl_compression.so from native/libgkl_compression.so (/mnt/outputs/gridss/SBJ_seqcii_020_tumor.bam.gridss.working/libgkl_compression4731184841171590862.so: /mnt/outputs/gridss/SBJ_seqcii_020_tumor.bam.gridss.working/libgkl_compression4731184841171590862.so: failed to map segment from shared object)
06:14:49.299 WARN  IntelDeflaterFactory - IntelInflater is not supported, using Java.util.zip.Inflater
10:55:38.470 WARN  IntelDeflaterFactory - IntelDeflater is not supported, using Java.util.zip.Deflater
WARNING 2020-04-09 12:16:00     AsyncBufferedIterator   Thread interrupt received whilst closing underlying iterator

**Comment by d-cameron** [comment]
This error is coming from the htsjdk library so unfortunately, I'm not able to help too much. I'd recommend raising an issue on https://github.com/samtools/htsjdk/ as they should have more info on these.

The errors and warnings seem to indicate that your OS and/or CPU version doesn't match the version expected by the bundled C code. I was under the impression that Docker was supposed to wrap these differences. Maybe your CPU is not reporting as a modern CPU?

**Comment by alexiswl** [comment]
Thanks Daniel, I'll try on a newer instance type and get back to you.

**Comment by alexiswl** [comment]
Hi Daniel after playing around a little bit it looks like the `/data` mount on the ec2-instance was accidentally set to noexec, remounting with exec permissions allowed me to resolve the issue - so happy to close. None of the additional warning also showed after this. Is there a reason why the jar files are copied out to the working directory? Could these be placed in a /tmp instead that generally has exec permissions?

**Comment by d-cameron** [comment]
You'd have to pose that question to the htsjdk team - I've just used the same approach as they have used. There's no advantage to GRIDSS using /tmp if the htsjdk library used within GRIDSS still writes to the directory that it does.
