### ISSUE TITLE
GRIDSS fails if inputs / outputs share filenames

### ISSUE THREAD

**Issue by illusional** [PapenfussLab/gridss#335]
I was using GRIDSS in a pipeline where the input bams had the same name and GRIDSS gave unexpected results. I was also careless and gave my output assembly the same name (all in different directories though) and it failed with an `ArrayIndexOutOfBoundsException` (stacktrace below).

Although it would be great if filenames didn't matter, is it possible to add a early error to gridss and fail if the input filenames will cause issues.

```
[Tue Apr 28 20:36:03 UTC 2020] gridss.AnnotateVariants done. Elapsed time: 0.06 minutes.
Runtime.totalMemory()=3054501888
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.ArrayList.elementData(ArrayList.java:422)
        at java.util.ArrayList.get(ArrayList.java:435)
        at au.edu.wehi.idsv.StructuralVariationCallBuilder.addEvidence(StructuralVariationCallBuilder.java:116)
        at gridss.AllocateEvidence.annotate(AllocateEvidence.java:104)
        at gridss.AllocateEvidence.lambda$iterator$1(AllocateEvidence.java:79)
        at com.google.common.collect.Iterators$6.transform(Iterators.java:820)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
        at com.google.common.collect.Iterators$5.computeNext(Iterators.java:663)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
        at au.edu.wehi.idsv.util.AutoClosingIterator.hasNext(AutoClosingIterator.java:47)
        at au.edu.wehi.idsv.SequentialCoverageAnnotator.hasNext(SequentialCoverageAnnotator.java:121)
        at au.edu.wehi.idsv.util.ParallelTransformIterator.hasNext(ParallelTransformIterator.java:67)
        at au.edu.wehi.idsv.util.AutoClosingIterator.hasNext(AutoClosingIterator.java:47)
        at com.google.common.collect.Iterators$PeekingImpl.hasNext(Iterators.java:1182)
        at au.edu.wehi.idsv.util.WindowedSortingIterator.advanceUnderlying(WindowedSortingIterator.java:71)
        at au.edu.wehi.idsv.util.WindowedSortingIterator.computeNext(WindowedSortingIterator.java:57)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
        at com.google.common.collect.Iterators$MergingIterator.<init>(Iterators.java:1322)
        at com.google.common.collect.Iterators.mergeSorted(Iterators.java:1291)
        at gridss.cmdline.VcfTransformCommandLineProgram.getAllCalls(VcfTransformCommandLineProgram.java:75)
        at gridss.cmdline.VcfTransformCommandLineProgram.doWork(VcfTransformCommandLineProgram.java:51)
        at gridss.cmdline.MultipleSamFileCommandLineProgram.doWork(MultipleSamFileCommandLineProgram.java:189)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
        at gridss.AnnotateVariants.main(AnnotateVariants.java:67)
```

Thanks!

**Comment by illusional** [comment]
I can provide some sample data if required, but here's the command line with the docker `gridss/gridss:2.6.3`:

```bash
/opt/gridss/gridss.sh \
  --threads 16 \
  --workingdir "./TMP" \
  --reference <inputsdir>/678825611/Homo_sapiens_assembly38.fasta \
  --output "generated.vcf" \
  --assembly "generated.bam" \
  --blacklist <inputsdir>/-1061297909/hg38-blacklist-renamed.v2.bed \
  <inputsdir>/-1272843053/generated.bam \
  <inputsdir>/-1030628362/generated.bam
```

**Comment by d-cameron** [comment]
Name check added to gridss.sh command line validation.
