### ISSUE TITLE
GeneratePonBedpe java error

### ISSUE THREAD

**Issue by drvenki** [PapenfussLab/gridss#336]
Hi I am trying to generate a panel of normals bedpe file for our own data from a list of germline VCFs we have. I keep running into this error and I am unable to generate the bedpe. 
Below is the error log. 
Please help. 
```
java -Xmx8g -cp /nfs/PROBIO/autoseq-scripts/gridss-2.7.2-gridss-jar-with-dependencies.jar gridss.GeneratePonBedpe $(ls -1 *.vcf | awk ' { print "INPUT=" $0 }' | head -$n) O=gridss_pon_breakpoint.bedpe SBO=pondir/gridss_pon_single_breakend.bed NO=1 Q=60.0 INCLUDE_IMPRECISE_CALLS=true REFERENCE_SEQUENCE=/nfs/PROBIO/autoseq-genome/genome/human_g1k_v37_decoy.fasta
INFO	2020-05-06 14:35:15	GeneratePonBedpe	
********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    GeneratePonBedpe -INPUT PB-P-Biobanking10-N-10-KH-C2-gridss.vcf -INPUT PB-P-Biobanking1-N-1-KH-PC-gridss.vcf -INPUT PB-P-Biobanking2-N-2-KH-C2-gridss.vcf -INPUT PB-P-Biobanking3-N-3-KH-C2-gridss.vcf -INPUT PB-P-Biobanking4-N-4-KH-C2-gridss.vcf -INPUT PB-P-Biobanking5-N-5-KH-C2-gridss.vcf -INPUT PB-P-Biobanking6-N-6-KH-C2-gridss.vcf -INPUT PB-P-Biobanking7-N-7-KH-C2-gridss.vcf -INPUT PB-P-Biobanking8-N-8-KH-C2-gridss.vcf -INPUT PB-P-Biobanking9-N-9-KH-C2-gridss.vcf -O gridss_pon_breakpoint.bedpe -SBO pondir/gridss_pon_single_breakend.bed -NO 1 -Q 60.0 -INCLUDE_IMPRECISE_CALLS true -REFERENCE_SEQUENCE /nfs/PROBIO/autoseq-genome/genome/human_g1k_v37_decoy.fasta
**********


14:35:15.332 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/nfs/PROBIO/autoseq-scripts/gridss-2.7.2-gridss-jar-with-dependencies.jar!/com/intel/gkl/native/libgkl_compression.so
[Wed May 06 14:35:15 CEST 2020] GeneratePonBedpe INPUT=[PB-P-Biobanking10-N-10-KH-C2-gridss.vcf, PB-P-Biobanking1-N-1-KH-PC-gridss.vcf, PB-P-Biobanking2-N-2-KH-C2-gridss.vcf, PB-P-Biobanking3-N-3-KH-C2-gridss.vcf, PB-P-Biobanking4-N-4-KH-C2-gridss.vcf, PB-P-Biobanking5-N-5-KH-C2-gridss.vcf, PB-P-Biobanking6-N-6-KH-C2-gridss.vcf, PB-P-Biobanking7-N-7-KH-C2-gridss.vcf, PB-P-Biobanking8-N-8-KH-C2-gridss.vcf, PB-P-Biobanking9-N-9-KH-C2-gridss.vcf] OUTPUT=gridss_pon_breakpoint.bedpe SINGLE_BREAKEND_OUTPUT=pondir/gridss_pon_single_breakend.bed NORMAL_ORDINAL=1 MIN_BREAKPOINT_QUAL=60.0 INCLUDE_IMPRECISE_CALLS=true REFERENCE_SEQUENCE=/nfs/PROBIO/autoseq-genome/genome/human_g1k_v37_decoy.fasta    MIN_BREAKEND_QUAL=428.0 WORKER_THREADS=12 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Wed May 06 14:35:15 CEST 2020] Executing as clinseq@merlin on Linux 4.15.0-99-generic amd64; OpenJDK 64-Bit Server VM 1.8.0_152-release-1056-b12; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.7.2-gridss
ERROR	2020-05-06 14:35:15	GeneratePonBedpe	Imprecise call inclusion not recommended due to overly aggressive PON matching.
INFO	2020-05-06 14:35:25	GridssConfiguration	maxCoverage=25000
INFO	2020-05-06 14:35:25	GridssConfiguration	minMapq=20
INFO	2020-05-06 14:35:25	GridssConfiguration	fallbackMapq=20
INFO	2020-05-06 14:35:25	GridssConfiguration	fallbackBaseq=20
INFO	2020-05-06 14:35:25	GridssConfiguration	minAnchorShannonEntropy=0.5
INFO	2020-05-06 14:35:25	GridssConfiguration	dovetailMargin=4
INFO	2020-05-06 14:35:25	GridssConfiguration	softclip.minAverageQual=5.0
INFO	2020-05-06 14:35:25	GridssConfiguration	softclip.minLength=5
INFO	2020-05-06 14:35:25	GridssConfiguration	softclip.minAnchorIdentity=0.95
INFO	2020-05-06 14:35:25	GridssConfiguration	softclip.realignSplitReads=false
INFO	2020-05-06 14:35:25	GridssConfiguration	useReadGroupSampleNameCategoryLabel=true
INFO	2020-05-06 14:35:25	GridssConfiguration	chunkSize=10000000
INFO	2020-05-06 14:35:25	GridssConfiguration	chunkSequenceChangePenalty=250000
INFO	2020-05-06 14:35:25	GridssConfiguration	hashEvidenceID=true
INFO	2020-05-06 14:35:25	GridssConfiguration	adapter=AGATCGGAAGAG
INFO	2020-05-06 14:35:25	GridssConfiguration	adapter=ATGGAATTCTCG
INFO	2020-05-06 14:35:25	GridssConfiguration	adapter=CTGTCTCTTATA
INFO	2020-05-06 14:35:25	GridssConfiguration	scoring.model=FastEmpiricalReferenceLikelihood
INFO	2020-05-06 14:35:25	GridssConfiguration	assembly.k=25
INFO	2020-05-06 14:35:25	GridssConfiguration	assembly.minReads=3
INFO	2020-05-06 14:35:25	GridssConfiguration	assembly.includePairAnchors=true
INFO	2020-05-06 14:35:25	GridssConfiguration	assembly.pairAnchorMismatchIgnoreEndBases=5
INFO	2020-05-06 14:35:25	GridssConfiguration	assembly.writeFiltered=false
INFO	2020-05-06 14:35:25	GridssConfiguration	assembly.anchorLength=300
INFO	2020-05-06 14:35:25	GridssConfiguration	assembly.removeMisassembledPartialContigsDuringAssembly=true
INFO	2020-05-06 14:35:25	GridssConfiguration	assembly.maxExpectedBreakendLengthMultiple=1.5
INFO	2020-05-06 14:35:25	GridssConfiguration	assembly.errorCorrection.collapseBubblesOnly=true
INFO	2020-05-06 14:35:25	GridssConfiguration	assembly.errorCorrection.maxBaseMismatchForCollapse=2
INFO	2020-05-06 14:35:25	GridssConfiguration	assembly.errorCorrection.maxPathCollapseLengthMultiple=2.0
INFO	2020-05-06 14:35:25	GridssConfiguration	assembly.realignContigs=true
INFO	2020-05-06 14:35:25	GridssConfiguration	assembly.downsample.acceptDensityPortion=0.1
INFO	2020-05-06 14:35:25	GridssConfiguration	assembly.downsample.targetEvidenceDensity=1
INFO	2020-05-06 14:35:25	GridssConfiguration	assembly.downsample.minimumDensityWindowSize=1000
INFO	2020-05-06 14:35:25	GridssConfiguration	assembly.positional.maxPathLengthMultiple=1.1
INFO	2020-05-06 14:35:25	GridssConfiguration	assembly.positional.retainWidthMultiple=2.0
INFO	2020-05-06 14:35:25	GridssConfiguration	assembly.positional.flushWidthMultiple=1.0
INFO	2020-05-06 14:35:25	GridssConfiguration	assembly.positional.maximumNodeDensity=2.0
INFO	2020-05-06 14:35:25	GridssConfiguration	assembly.positional.trimSelfIntersectingReads=true
INFO	2020-05-06 14:35:25	GridssConfiguration	assembly.positional.forceFullMemoizationRecalculationAt=0.8
INFO	2020-05-06 14:35:25	GridssConfiguration	assembly.positional.safetyModePathCountThreshold=50000
INFO	2020-05-06 14:35:25	GridssConfiguration	assembly.positional.safetyModeContigsToCall=3
INFO	2020-05-06 14:35:25	GridssConfiguration	assembly.contigNamePrefix=asm%d-
INFO	2020-05-06 14:35:25	GridssConfiguration	variantcalling.minReads=2
INFO	2020-05-06 14:35:25	GridssConfiguration	variantcalling.minScore=50.0
INFO	2020-05-06 14:35:25	GridssConfiguration	variantcalling.minSize=10
INFO	2020-05-06 14:35:25	GridssConfiguration	variantcalling.breakpointLowQuality=500.0
INFO	2020-05-06 14:35:25	GridssConfiguration	variantcalling.breakendLowQuality=1500.0
INFO	2020-05-06 14:35:25	GridssConfiguration	variantcalling.callUnassembledBreakpoints=true
INFO	2020-05-06 14:35:25	GridssConfiguration	variantcalling.callUnassembledBreakends=false
INFO	2020-05-06 14:35:25	GridssConfiguration	variantcalling.breakendMargin=10
INFO	2020-05-06 14:35:25	GridssConfiguration	variantcalling.writeFiltered=false
INFO	2020-05-06 14:35:25	GridssConfiguration	variantcalling.simplecalls=false
INFO	2020-05-06 14:35:25	GridssConfiguration	variantcalling.maxBreakendHomologyLength=300
INFO	2020-05-06 14:35:25	GridssConfiguration	variantcalling.breakendHomologyAlignmentMargin=10
INFO	2020-05-06 14:35:25	GridssConfiguration	variantcalling.requireAssemblyCategorySupport=true
INFO	2020-05-06 14:35:25	GridssConfiguration	variantcalling.callBreakends=true
INFO	2020-05-06 14:35:25	GridssConfiguration	variantcalling.includeSupportingReadNames=false
INFO	2020-05-06 14:35:25	GridssConfiguration	terminateOnFirstError=true
INFO	2020-05-06 14:35:25	GridssConfiguration	visualisation.directory=visualisation
INFO	2020-05-06 14:35:25	GridssConfiguration	visualisation.buffers=false
INFO	2020-05-06 14:35:25	GridssConfiguration	visualisation.bufferTrackingItervalInSeconds=60
INFO	2020-05-06 14:35:25	GridssConfiguration	visualisation.timeouts=false
INFO	2020-05-06 14:35:25	GridssConfiguration	visualisation.evidenceAllocation=false
INFO	2020-05-06 14:35:25	GridssConfiguration	visualisation.assemblyProgress=false
INFO	2020-05-06 14:35:25	GridssConfiguration	visualisation.assemblyTelemetry=false
INFO	2020-05-06 14:35:25	GridssConfiguration	visualisation.maxCliqueTelemetry=false
INFO	2020-05-06 14:35:25	GridssConfiguration	visualisation.assemblyGraph=false
INFO	2020-05-06 14:35:25	GridssConfiguration	visualisation.assemblyGraphFullSize=false
INFO	2020-05-06 14:35:25	GridssConfiguration	visualisation.assemblyContigMemoization=false
INFO	2020-05-06 14:35:25	TwoBitBufferedReferenceSequenceFile	Saving reference genome cache to /nfs/PROBIO/autoseq-genome/genome/human_g1k_v37_decoy.fasta.gridsscache
INFO	2020-05-06 14:35:25	TwoBitBufferedReferenceSequenceFile	Caching reference genome contig 1
[Wed May 06 14:35:25 CEST 2020] gridss.GeneratePonBedpe done. Elapsed time: 0.17 minutes.
Runtime.totalMemory()=1011351552
Exception in thread "main" htsjdk.tribble.TribbleException$MalformedFeatureFile: Unable to parse header with error: /media/clinseq/disk4/gridss_pon/pondir/PB-P-Biobanking10-N-10-KH-C2-gridss.vcf, for input source: file:///media/clinseq/disk4/gridss_pon/pondir/%1B%5B0m%1B%5B01;32mPB-P-Biobanking10-N-10-KH-C2-gridss.vcf%1B%5B0m
	at htsjdk.tribble.TribbleIndexedFeatureReader.readHeader(TribbleIndexedFeatureReader.java:263)
	at htsjdk.tribble.TribbleIndexedFeatureReader.<init>(TribbleIndexedFeatureReader.java:102)
	at htsjdk.tribble.TribbleIndexedFeatureReader.<init>(TribbleIndexedFeatureReader.java:127)
	at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:120)
	at htsjdk.tribble.AbstractFeatureReader.getFeatureReader(AbstractFeatureReader.java:80)
	at htsjdk.variant.vcf.VCFFileReader.<init>(VCFFileReader.java:140)
	at htsjdk.variant.vcf.VCFFileReader.<init>(VCFFileReader.java:92)
	at gridss.GeneratePonBedpe.getFilteredIterator(GeneratePonBedpe.java:143)
	at gridss.GeneratePonBedpe.filteredMerge(GeneratePonBedpe.java:127)
	at gridss.GeneratePonBedpe.doWork(GeneratePonBedpe.java:81)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
	at gridss.GeneratePonBedpe.main(GeneratePonBedpe.java:174)
Caused by: java.nio.file.NoSuchFileException: /media/clinseq/disk4/gridss_pon/pondir/PB-P-Biobanking10-N-10-KH-C2-gridss.vcf
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at htsjdk.samtools.seekablestream.SeekablePathStream.<init>(SeekablePathStream.java:39)
	at htsjdk.tribble.util.ParsingUtils.openInputStream(ParsingUtils.java:108)
	at htsjdk.tribble.TribbleIndexedFeatureReader.readHeader(TribbleIndexedFeatureReader.java:253)
	... 11 more
```
TIA,
Venkatesh Chellappa (Venki)

**Comment by d-cameron** [comment]
> Caused by: java.nio.file.NoSuchFileException: /media/clinseq/disk4/gridss_pon/pondir/PB-P-Biobanking10-N-10-KH-C2-gridss.vcf

It looks like you're missing an input file.

**Comment by d-cameron** [comment]
Also, GRIDSS 2.9.0 has GeneratePonBedpe improvements you may be interested in.

**Comment by drvenki** [comment]
I will upgrade my Gridss. Also the files are present in the directory. I tried with both .gz and .vcf files. Will upgrade and get back on this.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by d-cameron** [comment]
Which directory? You have multiple directories being written. Also, you're writing the bed and bedpe files to different directories which won't work for the somatic filter as it needs both a bedpe pon file for breakpoints and bed pon file for single breakends.

I'd recommend double-checking that you don't have any path issues by using absolute paths for all files.
