### ISSUE TITLE
Map file error

### ISSUE THREAD

**Issue by woodoo46** [PapenfussLab/gridss#345]
Hi, there,

I tried to run gridss on 3 samples, but I got this error, it seems it is a memory error, I gave the job 96G memory.  Thanks!

ERROR   2020-05-14 01:49:18     AssemblyEvidenceSource  Error assembling chunk 8 (chr1:80000001-chr1:90000000)
htsjdk.samtools.util.RuntimeIOException: Map failed
        at htsjdk.samtools.MemoryMappedFileBuffer.<init>(MemoryMappedFileBuffer.java:28)
        at htsjdk.samtools.AbstractBAMFileIndex.<init>(AbstractBAMFileIndex.java:64)
        at htsjdk.samtools.DiskBasedBAMFileIndex.<init>(DiskBasedBAMFileIndex.java:46)
        at htsjdk.samtools.BAMFileReader.getIndex(BAMFileReader.java:422)
        at htsjdk.samtools.BAMFileReader.createIndexIterator(BAMFileReader.java:1062)
        at htsjdk.samtools.BAMFileReader.query(BAMFileReader.java:615)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:533)
        at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.queryOverlapping(SamReader.java:405)
        at au.edu.wehi.idsv.SAMEvidenceSource.tryOpenReader(SAMEvidenceSource.java:265)
        at au.edu.wehi.idsv.SAMEvidenceSource.iterator(SAMEvidenceSource.java:241)
        at au.edu.wehi.idsv.SAMEvidenceSource.mergedIterator(SAMEvidenceSource.java:575)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:232)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:196)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$2(AssemblyEvidenceSource.java:98)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Map failed
        at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:939)
        at htsjdk.samtools.MemoryMappedFileBuffer.<init>(MemoryMappedFileBuffer.java:23)
        ... 17 more
**Caused by: java.lang.OutOfMemoryError: Map failed**
        at sun.nio.ch.FileChannelImpl.map0(Native Method)

**Comment by d-cameron** [comment]
How much physical memory do you have? Java memory mapped files are not stored on the heap so are not included in the 96GB.

Also, do you have enough file handles? See https://github.com/PapenfussLab/gridss/#too-many-open-files for another possible root cause.

How many worker threads are you running? The default is the number of cores available to the OS. If this is very high, OOM is likely since assembly memory scales linearly with the number of worker threads.

I recommend 8 worker threads, and a jvm heap size of 31GB. If you want to scale to more than this, I recommend running multiple instances of GRIDSS (with 8 workers /31gb). See https://github.com/PapenfussLab/gridss/#gridssh-steps for details.
