### ISSUE TITLE
GeneratePonBedpe AsyncVCF Error

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#348]
It ends with an error after a few seconds. A short excerpt is:

```
INFO    2020-05-18 00:12:14     GridssConfiguration     visualisation.assemblyGraph=false
INFO    2020-05-18 00:12:14     GridssConfiguration     visualisation.assemblyGraphFullSize=false
INFO    2020-05-18 00:12:14     GridssConfiguration     visualisation.assemblyContigMemoization=false
INFO    2020-05-18 00:12:14     TwoBitBufferedReferenceSequenceFile     Loading reference genome from cache /scratch/hm82/Reference/hs38DH.fasta.gridsscache
Exception in thread "AsyncVCF" Exception in thread "AsyncVCF" Exception in thread "AsyncVCF" Exception in thread "AsyncVCF" Exception in thread "AsyncVCF" Exception in thread "AsyncVCF" Exception in thread "AsyncVCF" Exception in thread "AsyncVCF" Exception in thread "AsyncVCF" [Mon May 18 00:12:14 AEST 2020] gridss.GeneratePonBedpe done. Elapsed time: 0.01 minutes.
java.lang.RuntimeException: java.lang.NullPointerException
        at au.edu.wehi.idsv.util.AsyncBufferedIterator$ReaderRunnable.run(AsyncBufferedIterator.java:189)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at gridss.GeneratePonBedpe.lambda$getFilteredIterator$6(GeneratePonBedpe.java:223)
        at com.google.common.collect.Iterators$5.computeNext(Iterators.java:664)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)

```

I also tried `THREADS=1` and the error persists.

```
Exception in thread "main" java.lang.NullPointerException
        at gridss.GeneratePonBedpe.lambda$getFilteredIterator$6(GeneratePonBedpe.java:223)
        at com.google.common.collect.Iterators$5.computeNext(Iterators.java:664)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
        at com.google.common.collect.Iterators$PeekingImpl.hasNext(Iterators.java:1182)
```

**Comment by d-cameron** [comment]
Fixed in dev. Workaround until next release is to filter out all `IMPRECISE` calls in the input VCF. E.g:
```
grep -v IMPRECISE input.vcf > input.precise.vcf
java -cp gridss.jar gridss.GeneratePonBedpe O=pon.bed SBO=pon.bedpe R=reference.fasta NORMAL_ORDINAL=0 I=input.precise.vcf
```

**Comment by DarioS** [comment]
Should the error be downgraded to a warning? It seems more like a warning than something really bad.

```
INFO    2020-05-20 16:43:03     TwoBitBufferedReferenceSequenceFile     Loading reference genome complete
ERROR   2020-05-20 16:43:35     GeneratePonBedpe        Imprecise call inclusion not recommended due to overly aggressive PON matching.
[Wed May 20 16:43:35 AEST 2020] gridss.GeneratePonBedpe done. Elapsed time: 0.61 minutes.
```

The BED and BEDPE files are created. Should imprecise call exclusion be the default action?

**Comment by drvenki** [comment]
I was breaking my head and trying to look what is happening with my java. The simple things are often missed easily! Thanks for this thread DarioS and d-cameron. 
got my ponbedpe and ponbed files. 
Waiting for the updates! 
Thanks,
Venkatesh Chellappa

**Comment by d-cameron** [comment]
>Should the error be downgraded to a warning? It seems more like a warning than something really bad.

The downstream impact of adding imprecise variants is significant enough that I gave it an error label instead of a warning. If your coverage is really high, you'll get a background of reads treated as discordant read pairs just because they come from unusually long fragments.  These will all be imprecise calls (DP-only support, since there isn't actually any breakpoint). Creating a PON from these will essentially filter out small deletion events since, once you have enough of them in pon, your background noise will cover the whole genome.

Resolving this requires something akin to how CLEVER fits local fragment size distribution against a model. GRIDSS does not yet do this.
