### ISSUE TITLE
Questions about running gridss

### ISSUE THREAD

**Issue by ehsueh** [PapenfussLab/gridss#38]
Thank you for putting together this neat tool. :smile: 

I have been playing around and experimenting with GRIDSS. Currently I am stuck on an error message that I'm not sure how to solve. Would you be able to help me out? 

My command:

`java -ea -Xmx32g -cp bin/gridss-0.11.7-jar-with-dependencies.jar au.edu.wehi.idsv.Idsv TMP_DIR=tmp WORKING_DIR=working REFERENCE=x.fasta INPUT=x.bam OUTPUT=x.gridss.vcf PER_CHR=TRUE WORKER_THREADS=12`

GRIDSS ran smoothly in the beginning despite the warnings on insert size out of range on some records. Then later on I get a fatal exception. I've quoted the error messages and the trace stack below.

> ERROR	2016-09-28 10:08:15	Idsv	Fatal exception thrown by worker thread.
htsjdk.samtools.SAMException: Exception when processing alignment for BAM index SN822:332:HWYWFBCXX:1:1107:10552:2088 2/2 150b aligned read.
	at htsjdk.samtools.BAMFileWriter.writeAlignment(BAMFileWriter.java:131)
	at htsjdk.samtools.SAMFileWriterImpl.addAlignment(SAMFileWriterImpl.java:190)
	at au.edu.wehi.idsv.pipeline.ExtractEvidence.processInputRecords(ExtractEvidence.java:329)
	at au.edu.wehi.idsv.pipeline.ExtractEvidence.doProcess(ExtractEvidence.java:194)
	at au.edu.wehi.idsv.pipeline.ExtractEvidence.process(ExtractEvidence.java:150)
	at au.edu.wehi.idsv.SAMEvidenceSource.completeSteps(SAMEvidenceSource.java:91)
	at au.edu.wehi.idsv.Idsv$2$1.call(Idsv.java:380)
	at au.edu.wehi.idsv.Idsv$2$1.call(Idsv.java:376)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: htsjdk.samtools.SAMException: Exception creating BAM index for record SN822:332:HWYWFBCXX:1:1107:10552:2088 2/2 150b aligned read.
	at htsjdk.samtools.BAMIndexer.processAlignment(BAMIndexer.java:110)
	at htsjdk.samtools.BAMFileWriter.writeAlignment(BAMFileWriter.java:128)
	... 11 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 32783
	at htsjdk.samtools.BinningIndexBuilder.processFeature(BinningIndexBuilder.java:136)
	at htsjdk.samtools.BAMIndexer$BAMIndexBuilder.processAlignment(BAMIndexer.java:213)
	at htsjdk.samtools.BAMIndexer.processAlignment(BAMIndexer.java:108)
	... 12 more

May I also ask where I could find additional readings describing GRIDSS's algorithm and workflow?

Thank you for your time!

**Comment by d-cameron** [comment]
Your usage looks correct, but I haven't encountered that error message before. From the error log, it looks like an error in the input BAM. I would recommend trying the following:

- Run Picard tools [ValidateSAMFile](https://broadinstitute.github.io/picard/command-line-overview.html#ValidateSamFile).
- Run Picard tools [FixMateInformation](https://broadinstitute.github.io/picard/command-line-overview.html#FixMateInformation)

If GRIDSS does fails even after issues raised by both of those have been resolved, could you run GRIDSS with `VERBOSITY=DEBUG`, and attach the log file and the lines of the BAM file that GRIDSS failed on.

The GRIDSS paper which provides details on the GRIDSS algorithms should be out soon.

**Comment by ehsueh** [comment]
It seems like I am getting the same insert size out of range problems when I diagnose with two Picard tools you recommended. 

I've tried multiple different BAM's (generated from bwa mem) but I'm getting the same problems. Perhaps I need to change the parameters for bwa mem. Without knowing more about the details of how GRIDSS works, I'm not sure how to optimize my input for the software. Could you please provide an example of the bwa mem command you used for alignment and the samtools view command you used to filter and convert sam to bam? 

Thanks again.

**Comment by d-cameron** [comment]
Did you manage to get it working? It sounds like your BAM file might be corrupt. Converting to BAM->SAM->BAM might work.
In terms of parameters, a minimal bwa/picard tools command line such as
`bwa mem hg19.bwa reads.1.fq reads.2.fq | AddOrReplaceReadGroups I=/dev/stdin O=out.unsorted.bam ;  SortSam I=out.unsorted.bam O=sorted.bam SO=coordinate`
should work.

Another option is that you're running an old version of bwa. Is you version older that 0.7.*?

**Comment by ehsueh** [comment]
Thanks for getting back to me. I am using bwa0.7.15. 

Picard has been giving me the same "insert size out of range" when I run the validation or fix and when I try to perform the AddOrReplaceReadGroups command. I've tried regenerating my SAM and I've also tried multiple different samples with no success. 

> DEBUG	2016-10-25 18:23:43	AsyncBufferedIterator	Starting thread x1_bwa.sorted.nodup.bam-Metrics
DEBUG	2016-10-25 18:23:43	AsyncBufferedIterator	Starting thread x2_bwa.sorted.nodup.bam-Metrics
DEBUG	2016-10-25 18:23:44	AsyncBufferedIterator	Starting thread x3_bwa.sorted.nodup.bam-Metrics
INFO	2016-10-25 18:24:05	ExtractEvidence	Writing metrics
INFO	2016-10-25 18:24:07	ExtractEvidence	Writing metrics
...
INFO	2016-10-25 18:24:17	ExtractEvidence	Writing metrics
DEBUG	2016-10-25 18:28:34	BlockCompressedOutputStream	Using deflater: Deflater
...
DEBUG	2016-10-25 18:28:46	BlockCompressedOutputStream	Using deflater: Deflater
DEBUG	2016-10-25 18:28:46	AsyncBufferedIterator	Starting thread x2_bwa.sorted.nodup.bam-Extract
INFO	2016-10-25 18:28:47	SAMEvidenceSource	FAILURE extract evidence for x2_bwa.sorted.nodup.bam
ERROR	2016-10-25 18:28:47	SAMEvidenceSource	
htsjdk.samtools.SAMException: Exception when processing alignment for BAM index SN822:332:HWYWFBCXX:1:2110:19421:98057 2/2 99b aligned read.
	at htsjdk.samtools.BAMFileWriter.writeAlignment(BAMFileWriter.java:131)
	at htsjdk.samtools.SAMFileWriterImpl.addAlignment(SAMFileWriterImpl.java:190)
	at au.edu.wehi.idsv.pipeline.ExtractEvidence.processInputRecords(ExtractEvidence.java:329)
	at au.edu.wehi.idsv.pipeline.ExtractEvidence.doProcess(ExtractEvidence.java:194)
	at au.edu.wehi.idsv.pipeline.ExtractEvidence.process(ExtractEvidence.java:150)
	at au.edu.wehi.idsv.SAMEvidenceSource.completeSteps(SAMEvidenceSource.java:91)
	at au.edu.wehi.idsv.Idsv$2$1.call(Idsv.java:380)
	at au.edu.wehi.idsv.Idsv$2$1.call(Idsv.java:376)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: htsjdk.samtools.SAMException: Exception creating BAM index for record SN822:332:HWYWFBCXX:1:2110:19421:98057 2/2 99b aligned read.
	at htsjdk.samtools.BAMIndexer.processAlignment(BAMIndexer.java:110)
	at htsjdk.samtools.BAMFileWriter.writeAlignment(BAMFileWriter.java:128)
	... 11 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 32783
	at htsjdk.samtools.BinningIndexBuilder.processFeature(BinningIndexBuilder.java:136)
	at htsjdk.samtools.BAMIndexer$BAMIndexBuilder.processAlignment(BAMIndexer.java:213)
	at htsjdk.samtools.BAMIndexer.processAlignment(BAMIndexer.java:108)
	... 12 more

Corresponding info from BAM (these are on line 96328 and 96331 of the bam file, respectively.)

> SN822:332:HWYWFBCXX:1:2110:19421:98057	99	chrx	537126263	60	150M	=	537126531	366	CTCGACAGGTGCATAATCCCTATGAGTAAATTAGGCCCACTGACATTGGCAAATATACTATCTGCCGTCAAGTTTCAGTTTTCTTTTCGGTTTTTGGACGTTGGCAACTTGGCATAGGTTCGAGGAGGCCGCCGAGCAGTTCAGGCTGGA	GGGGGIIIIIIIIIIIIIGIIIIIGIIIIIGIIIGIIIIIIGGIIIIGIGGIIIIIIIIIGIIGIIIIIIIIGGGGGIIGGGIIIIIGGGGGGIIGGGGGIGGGIIIIGIIGIGIIGIGGIGGGIGGIIGIIIIIIIGIIIIIIGIIIGG	MD:Z:150	PG:Z:MarkDuplicates	RG:Z:2016-09-16-19-53-40_x2	NM:i:0	AS:i:150	XS:i:20
SN822:332:HWYWFBCXX:1:2110:19421:98057	147	chrx	537126531	60	6M1I92M	=	537126263	-366	TACTGTAAAAAAAAAAATCAGTTATGCCATGTATATATAGCTAATGTCTTTGAGGCAAGATGCAAAATTTTGTTGTTAGTGCGTAGTTCAAGAACTTTG	<<.GAGGGGGAGGIIGIIGGIGGGGGGGIIIIGIGIGGGGGIIIIIIIIIIIGGGGGIIIIIGGGGIIGIIIIGIGGIGGGGIGGGIGIIIIIGGGGGG	MD:Z:98	PG:Z:MarkDuplicates	RG:Z:2016-09-16-19-53-40_x2	NM:i:1	AS:i:92	XS:i:20

If I just do:
`bwa mem ... | samtools view -b ` 
(i.e. add info for read group without the picard step), the process crashed with a different error. I'm not sure which line of bam it crashed on or if it's already done going trhough the bam.

> INFO	2016-10-25 18:03:45	GridssConfiguration	visualisation.timeouts=true
INFO	2016-10-25 18:03:45	GridssConfiguration	visualisation.evidenceAllocation=false
INFO	2016-10-25 18:03:45	GridssConfiguration	visualisation.assemblyProgress=true
INFO	2016-10-25 18:03:45	GridssConfiguration	visualisation.assemblyGraph=false
INFO	2016-10-25 18:03:45	GridssConfiguration	visualisation.assemblyGraphFullSize=false
INFO	2016-10-25 18:03:45	GridssConfiguration	visualisation.assemblyContigMemoization=false
DEBUG	2016-10-25 18:03:45	GenomicProcessingContext	Loading reference genome cache on background thread.
DEBUG	2016-10-25 18:03:45	TwoBitBufferedReferenceSequenceFile	Loading entire reference genome into memory
INFO	2016-10-25 18:03:45	Idsv	Loading aligner
DEBUG	2016-10-25 18:03:45	AlignerFactory	Unable to load sswjni library
DEBUG	2016-10-25 18:03:46	AlignerFactory	Created ./tmp/ee4c0d79-0252-485c-95c2-29a7312be611-libsswjni.so
DEBUG	2016-10-25 18:03:46	AlignerFactory	Testing JNI alignment
INFO	2016-10-25 18:03:46	AlignerFactory	sswjni library loading successful.
INFO	2016-10-25 18:03:46	Idsv	Using 10 worker threads
INFO	2016-10-25 18:03:46	Idsv	Extracting evidence.
INFO	2016-10-25 18:03:46	SAMEvidenceSource	START extract evidence for data/map_bwamem/test/1.bam
DEBUG	2016-10-25 18:03:46	AsyncBufferedIterator	Starting thread 1.bam-Metrics
ERROR	2016-10-25 18:03:47	Idsv	Exception thrown from background taskjava.lang.AssertionError
DEBUG	2016-10-25 18:03:47	Idsv	Shutting down thread pool.
DEBUG	2016-10-25 18:03:47	Idsv	Waiting for thread pool tasks to complete
[Tue Oct 25 18:03:47 CDT 2016] au.edu.wehi.idsv.Idsv done. Elapsed time: 0.03 minutes.
Runtime.totalMemory()=2058354688
Exception in thread "main" java.lang.RuntimeException: Exception thrown from background task
	at au.edu.wehi.idsv.Idsv.doWork(Idsv.java:313)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:208)
	at au.edu.wehi.idsv.Idsv.main(Idsv.java:475)
Caused by: java.lang.AssertionError
	at au.edu.wehi.idsv.SequentialCoverageThreshold.acceptRecord(SequentialCoverageThreshold.java:24)
	at au.edu.wehi.idsv.pipeline.ExtractEvidence.processMetrics(ExtractEvidence.java:273)
	at au.edu.wehi.idsv.pipeline.ExtractEvidence.gatherMetrics(ExtractEvidence.java:161)
	at au.edu.wehi.idsv.pipeline.ExtractEvidence.process(ExtractEvidence.java:146)
	at au.edu.wehi.idsv.SAMEvidenceSource.completeSteps(SAMEvidenceSource.java:91)
	at au.edu.wehi.idsv.Idsv$2$1.call(Idsv.java:380)
	at au.edu.wehi.idsv.Idsv$2$1.call(Idsv.java:376)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Thanks again.

**Comment by d-cameron** [comment]
That particular error is caused by the input records being out of order. Did you coordinate sort your data before feeding to GRIDSS? I'll put a friendlier error message into the next release of GRIDSS as that error message is both ugly and uninformative.

**Comment by d-cameron** [comment]
I've finally tracked down your problem:

> SN822:332:HWYWFBCXX:1:2110:19421:98057 99 **chrx 537126263** 60 150M = 537126531 366 ...

BAM indexes (.bai) appear to have a maximum chromosome length of 2^29-1 (512Mb) which this alignment falls outside of. It would seem that your chromosome is short enough to be written to bam, but too long to be indexed. Unfortunately, I just call out to the htsjdk/picard library code for file I/O so there's not much I can do in GRIDSS.

See https://sourceforge.net/p/samtools/mailman/message/28141607/ for some discussion regarding these limits.

**Comment by ehsueh** [comment]
Hi Daniel,
Thank you for tracking down the issue. Just wanted follow up and let you know that after splitting my chromosomes into smaller partitions, I was able to run GRIDSS successfully on my data!
