### ISSUE TITLE
GRIDSS fails at AnnotateVariants with exit code 1/ --picardoptions non responsive

### ISSUE THREAD

**Issue by mas160** [PapenfussLab/gridss#384]
Hi,

I have been using GRIDSS which has been running for days now and it fails at the calling step more precisely the AnnotateVariants step with the following error message:
INFO    2020-08-19 08:48:36     TwoBitBufferedReferenceSequenceFile     Loading reference genome complete              Exception in thread "filout.bam-Coverage" java.lang.RuntimeException: java.lang.IllegalStateException: Record E00433:216:H2JHHCCX2:2:1112:13220:48757     147     NC_023660.1     7513074 60      151M    =       7512998 -227    TGGAAGCTCCTGGAAAAGCAGATTTTTTTTTTCTTAGATTAAGGTAGAAGCAGCTCAGTGTCTAGAGCGAGGGAAATAATAGTCTTGCTGAGCCCTGTGCTTTCTAGACCAGATCTGTCTTGTGTCTGTGTCCACTTCCGAGGTGCCTGTT FJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJAJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFFFAA MC:Z:128M       MD:Z:151        NM:i:0  AS:i:151        XS:i:21 should come after E00433:216:H2JHHCCX2:2:1118:4269:2698 83      NC_023650.1     75405012        60      128M    =       75404740        -400    TTGAAATATTTGTTGTTCTAACAATGTTTAGCAATAAACACACAATCCAGTACACTAAAACAGGAAAAATGACAAAGCCATGAAGATGTGAGCAAAATGAGATCCTGCAAGGTGTCTCAATGTAATTC        JJFJFJFJJFJFFFAFF<JFFAJF7F<FJA7-JJFJJF-JJJJFA-<F7--JJJFFJJJJJJJFJJJJJJJJJJF<7A-7FA<AAF--JF-FJJJJJA-F<JJJJJJJJF-<FFJJJJFFJJFA--A<        MC:Z:109M5D38M4S        MD:Z:103G24     NM:i:1  AS:i:123        XS:i:22 when sorting with coordinate ordering.
        at au.edu.wehi.idsv.util.AsyncBufferedIterator$ReaderRunnable.run(AsyncBufferedIterator.java:189)
        at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.IllegalStateException: Record E00433:216:H2JHHCCX2:2:1112:13220:48757      147     NC_023660.1     7513074 60      151M    =       7512998 -227    TGGAAGCTCCTGGAAAAGCAGATTTTTTTTTTCTTAGATTAAGGTAGAAGCAGCTCAGTGTCTAGAGCGAGGGAAATAATAGTCTTGCTGAGCCCTGTGCTTTCTAGACCAGATCTGTCTTGTGTCTGTGTCCACTTCCGAGGTGCCTGTT FJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJAJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFFFAA MC:Z:128M       MD:Z:151        NM:i:0  AS:i:151        XS:i:21 should come after E00433:216:H2JHHCCX2:2:1118:4269:2698 83      NC_023650.1     75405012        60      128M    =       75404740        -400    TTGAAATATTTGTTGTTCTAACAATGTTTAGCAATAAACACACAATCCAGTACACTAAAACAGGAAAAATGACAAAGCCATGAAGATGTGAGCAAAATGAGATCCTGCAAGGTGTCTCAATGTAATTC        JJFJFJFJJFJFFFAFF<JFFAJF7F<FJA7-JJFJJF-JJJJFA-<F7--JJJFFJJJJJJJFJJJJJJJJJJF<7A-7FA<AAF--JF-FJJJJJA-F<JJJJJJJJF-<FFJJJJFFJJFA--A<        MC:Z:109M5D38M4S        MD:Z:103G24     NM:i:1  AS:i:123        XS:i:22 when sorting with coordinate ordering.
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:578)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:553)                                                 at au.edu.wehi.idsv.util.AsyncBufferedIterator$ReaderRunnable.run(AsyncBufferedIterator.java:166)
        ... 1 more
[Wed Aug 19 08:48:36 EDT 2020] gridss.AnnotateVariants done. Elapsed time: 0.10 minutes.
Runtime.totalMemory()=3414163456
Exception in thread "main" java.lang.IllegalStateException: Record E00433:216:H2JHHCCX2:2:1112:13220:48757      147     NC_023660.1     7513074 60      151M    =       7512998 -227    TGGAAGCTCCTGGAAAAGCAGATTTTTTTTTTCTTAGATTAAGGTAGAAGCAGCTCAGTGTCTAGAGCGAGGGAAATAATAGTCTTGCTGAGCCCTGTGCTTTCTAGACCAGATCTGTCTTGTGTCTGTGTCCACTTCCGAGGTGCCTGTT FJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJAJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFFFAA MC:Z:128M       MD:Z:151        NM:i:0  AS:i:151        XS:i:21 should come after E00433:216:H2JHHCCX2:2:1118:4269:2698 83      NC_023650.1     75405012        60      128M    =       75404740        -400    TTGAAATATTTGTTGTTCTAACAATGTTTAGCAATAAACACACAATCCAGTACACTAAAACAGGAAAAATGACAAAGCCATGAAGATGTGAGCAAAATGAGATCCTGCAAGGTGTCTCAATGTAATTC        JJFJFJFJJFJFFFAFF<JFFAJF7F<FJA7-JJFJJF-JJJJFA-<F7--JJJFFJJJJJJJFJJJJJJJJJJF<7A-7FA<AAF--JF-FJJJJJA-F<JJJJJJJJF-<FFJJJJFFJJFA--A<        MC:Z:109M5D38M4S        MD:Z:103G24     NM:i:1  AS:i:123        XS:i:22 when sorting with coordinate ordering.          at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:578)                                                 at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:553)                                                 at au.edu.wehi.idsv.util.AsyncBufferedIterator$ReaderRunnable.run(AsyncBufferedIterator.java:166)
        at java.base/java.lang.Thread.run(Thread.java:830)

Do I need to redo all the assembly or is the issue with the input .bam file? How do you think this can be solved? Or is it possible to bypass this error and still generate the vcf file?
The input .bam file was generated using bwa mem -t8 -C -p reference.fa reads.fq.gz | samtools view -Sb - > filout.bam
I also tried using --picardoptions VALIDATION_STRINGENCY=LENIENT but picard is ignoring the option and keeps on running with STRICT.I also tried modifying directly in gridss.sh with the following line: picardoptions="VALIDATION_STRINGENCY=LENIENT"
But picard is still ignoring that change...  How can I modify this option? Could you dircet me to the exact location of the file containing all the picard options used by gridss so that I can modify the validationstrigency option at the source?
Hoping to hear from you soon.
Thank you for your time and help,

**Comment by d-cameron** [comment]
> or is the issue with the input .bam file?
>bwa mem -t8 -C -p reference.fa reads.fq.gz | samtools view -Sb - > filout.bam

Your input bam is not coordinate sorted.

> I also tried using --picardoptions VALIDATION_STRINGENCY=LENIENT 

Incorrect sort order is a validation that can't be ignored by chaning `VALIDATION_STRINGENCY`. htsjdk treats it as a fatal error unless you explicitly set the code to ignore sort order. GRIDSS does not do this because the input file must be sorted.

> Do I need to redo all the assembly

Assembly is still valid as GRIDSS internally does re-sorting on the reads of interest. It's only at the file `AnnotateVariants` step where the input file sort order matters (GRIDSS needs the correct sort order to calculate the reference coverage annotations).

> How do you think this can be solved? 

```
mv filout.bam filout.unsorted.bam; samtool sort -o filout.bam filout.unsorted.bam
```
That is, rerun GRIDSS with the same input filename and location, just with the file sorted. If it's not the same filename then the GRIDSS rerun won't like it.
