### ISSUE TITLE
AnnotateVariantsRepeatMasker Fails For One Patient

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/gridss#408]
I run gridss_annotate_vcf_repeatmasker.sh and it works for 25 VCF files but fails on only one file. From the log, I see 

```
[Thu Oct 01 06:55:56 AEST 2020] gridss.InsertedSequencesToFasta done. Elapsed time: 1.67 minutes.
Runtime.totalMemory()=66584576
WARN: breaking loop in fragments
WARN: breaking loop in fragments
```

The warning does not appear in the log for any other sample apart from the one that fails.

Eventually, the error is

```
[Thu Oct 01 09:00:46 AEST 2020] gridss.repeatmasker.AnnotateVariantsRepeatMasker done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=2058354688
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 14
	at au.edu.wehi.idsv.repeatmasker.RepeatMaskerCodec.decodeSummary(RepeatMaskerCodec.java:133)
	at au.edu.wehi.idsv.repeatmasker.RepeatMaskerCodec.decode(RepeatMaskerCodec.java:52)
	at au.edu.wehi.idsv.repeatmasker.RepeatMaskerCodec.decode(RepeatMaskerCodec.java:17)
```

Could be that quirky RepeatMasker syntax causing a problem.

**Comment by d-cameron** [comment]
Fix for this is already in dev. RepeatMasker doesn't output an empty .fa.out when there's no repeats found. Instead it outputs the text:
```
There were no repetitive sequences detected in <file.fa>
```
Which of course doesn't parse.
