### ISSUE TITLE
Assembly exceptions

### ISSUE THREAD

**Issue by willhooper** [PapenfussLab/gridss#463]
Hi,

Occasionally, assembly will fail for me with one of two errors listed below. I'm splitting assembly across three jobs, with 8 threads per job. When running assembly on 500 samples separately (all aligned to the same reference), 5 fail with `java.util.ConcurrentModificationException` and 4 fail with `java.lang.NullPointerException`. Attempting these failed runs a second time seems to be successful. Have you seen this issue before? I'm not sure if this is a bug, or if there's something I can do on my end to mitigate this. 

 

### java.util.ConcurrentModificationException
```
INFO	2021-02-09 20:30:08	AssemblyEvidenceSource	Starting assembly on chunk 5 (chr1:50000001-chr1:60000000)
INFO	2021-02-09 20:30:08	AssemblyEvidenceSource	Starting assembly on chunk 2 (chr1:20000001-chr1:30000000)
INFO	2021-02-09 20:30:08	AssemblyEvidenceSource	Starting assembly on chunk 11 (chr1:110000001-chr1:120000000)
INFO	2021-02-09 20:30:08	AssemblyEvidenceSource	Starting assembly on chunk 8 (chr1:80000001-chr1:90000000)
INFO	2021-02-09 20:30:08	AssemblyEvidenceSource	Starting assembly on chunk 14 (chr1:140000001-chr1:150000000)
INFO	2021-02-09 20:30:08	AssemblyEvidenceSource	Starting assembly on chunk 17 (chr1:170000001-chr1:180000000)
INFO	2021-02-09 20:30:08	AssemblyEvidenceSource	Starting assembly on chunk 20 (chr1:200000001-chr1:210000000)
INFO	2021-02-09 20:30:08	AssemblyEvidenceSource	Starting assembly on chunk 23 (chr1:230000001-chr1:240000000)
ERROR	2021-02-09 20:30:08	AssemblyEvidenceSource	Error assembling chunk 20 (chr1:200000001-chr1:210000000)
java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1353)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.getHeader(AssemblyEvidenceSource.java:567)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:188)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$2(AssemblyEvidenceSource.java:100)
	at au.edu.wehi.idsv.AssemblyEvidenceSource$$Lambda$52/1961173763.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

### java.lang.NullPointerException
```
INFO	2021-02-09 21:56:31	AssemblyEvidenceSource	Starting assembly on chunk 5 (chr1:50000001-chr1:60000000)
INFO	2021-02-09 21:56:31	AssemblyEvidenceSource	Starting assembly on chunk 11 (chr1:110000001-chr1:120000000)
INFO	2021-02-09 21:56:31	AssemblyEvidenceSource	Starting assembly on chunk 2 (chr1:20000001-chr1:30000000)
INFO	2021-02-09 21:56:31	AssemblyEvidenceSource	Starting assembly on chunk 8 (chr1:80000001-chr1:90000000)
INFO	2021-02-09 21:56:31	AssemblyEvidenceSource	Starting assembly on chunk 14 (chr1:140000001-chr1:150000000)
INFO	2021-02-09 21:56:31	AssemblyEvidenceSource	Starting assembly on chunk 17 (chr1:170000001-chr1:180000000)
INFO	2021-02-09 21:56:31	AssemblyEvidenceSource	Starting assembly on chunk 20 (chr1:200000001-chr1:210000000)
INFO	2021-02-09 21:56:31	AssemblyEvidenceSource	Starting assembly on chunk 23 (chr1:230000001-chr1:240000000)
ERROR	2021-02-09 21:56:31	AssemblyEvidenceSource	Error assembling chunk 11 (chr1:110000001-chr1:120000000)
java.lang.NullPointerException
	at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$getHeader$16(AssemblyEvidenceSource.java:567)
	at au.edu.wehi.idsv.AssemblyEvidenceSource$$Lambda$53/66592217.test(Unknown Source)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.getHeader(AssemblyEvidenceSource.java:567)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:188)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$2(AssemblyEvidenceSource.java:100)
	at au.edu.wehi.idsv.AssemblyEvidenceSource$$Lambda$52/1961173763.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by d-cameron** [comment]
Thanks for the helpful error messages. The fix will be included in the next release.
