### ISSUE TITLE
Weird Java error which seems to relate to specific sequence in BAM file

### ISSUE THREAD

**Issue by ms3389** [PapenfussLab/gridss#487]
Hello,

I'm having a weird Java error which seems to relate to specific sequence in BAM file. Please see attached for the GRIDSS log.

Any thoughts?

Thanks

[gridss.full.20210414_015122.23213.log](https://github.com/PapenfussLab/gridss/files/6308491/gridss.full.20210414_015122.23213.log)

**Comment by alexiswl** [comment]
Hello, looks like your bams aren't sorted by coordinate - you may need to run `samtools sort -o output.sorted.bam input.bam` first before retrying

```
Caused by: java.lang.IllegalStateException: Record M00590:553:000000000-DC38H:1:1101:12852:1880	147	seq1	29818	60	150M	=	29722	-246	TGTCACACAAGCTCCTTAACCTTCCATGTCTCNATTTTCNNNNCNGTGAAGNAGGTATAAGAAGNCNTATCTNNTAGGNATGCTGTGAGCATTAAATAAAGGTACACATGGAAAACACCAGTCCTGGTGCAGTGAGAGTTCGGTGCATAC	HHD@0F@C<0/?1FFF1B1?CF1GF10/<?//#1/F???####?#1F/?/?#FDF2DB1/>?>?#?#/F>B/##/AB/#10/1CDFFA1BFGEHGAHFGDFB22FF12DB2BEA0FA0A0A0FAB01G1F1F1C3G1E@DDC1FB1>>1>	MC:Z:138M12S	MD:Z:32C6T0T0C0T1T6T12T1C5C0A4G71	NM:i:12	AS:i:126	XS:i:0 should come after M00590:553:000000000-DC38H:1:1101:19657:1901	99	seq1	3804	60	4S122M24S	=	3799	121	CTAGAGGGTCTCGCTCTGTCGCCCAGGCTTGACTGCAGTGGTGCAATCGCACCTCACTGCAACCTCCACCTCCCAGATTCAAGCAATTCTCCTGCCTCAGCCTCCTGANNAGCTGGCATTACNGGCTNTCTCTTATACNNATNTNCGNNC	1>11>@CAAFFF1AEEGGFF0FAE0BB0FG0GHHHHB1110DBFGHHE/AA/EBGCHAD1G1A0BGC00GHHCFEFABFFHFFHF0FG@2BFGBFGFHGBF>GGHHHB##>?/>/0/FGGD>#/??F#??<FEDGEFF##??#/#<<##?	MC:Z:24S126M	MD:Z:44T59G0T12A3	NM:i:4	AS:i:111	XS:i:33 when sorting with coordinate ordering.
	at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:578)
	at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:553)
	at au.edu.wehi.idsv.util.AsyncBufferedIterator$ReaderRunnable.run(AsyncBufferedIterator.java:166)
	... 1 more
```

**Comment by ms3389** [comment]
That solved it - thanks! That's what I get for doing work at 3AM.
