### ISSUE TITLE
About RepeatMasker's search engine

### ISSUE THREAD

**Issue by ken0-1n** [PapenfussLab/gridss#494]
Hi, I'm trying to use GRIDSS_annotate_vcf_repeatmasker.sh. I'm thinking of using HMMER as the search engine for RepeatMasker.
When I run RepeatMasker with HMMER as the search engine, I get bit score instead of SW in rm.fa.out.

Does GRIDSS support the output with HMMER as the search engine?

**Comment by ken0-1n** [comment]
I ran GRIDSS_annotate_vcf_repeatmasker.sh (2.11.1) and got an error. 

```
Exception in thread "main" htsjdk.tribble.TribbleException$MalformedFeatureFile: Error parsing LineIteratorImpl(SynchronousLineReader) at the first record, for input source: ./gridss.vcf.fa.out
        at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.readNextRecord(TribbleIndexedFeatureReader.java:396)
        at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.<init>(TribbleIndexedFeatureReader.java:342)
        at htsjdk.tribble.TribbleIndexedFeatureReader.iterator(TribbleIndexedFeatureReader.java:309)
        at gridss.repeatmasker.AnnotateVariantsRepeatMasker.doWork(AnnotateVariantsRepeatMasker.java:64)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at gridss.repeatmasker.AnnotateVariantsRepeatMasker.main(AnnotateVariantsRepeatMasker.java:100)
Caused by: java.lang.NumberFormatException: For input string: "bit"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:652)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at au.edu.wehi.idsv.repeatmasker.RepeatMaskerCodec.decodeSummary(RepeatMaskerCodec.java:94)
        at au.edu.wehi.idsv.repeatmasker.RepeatMaskerCodec.decode(RepeatMaskerCodec.java:52)
        at au.edu.wehi.idsv.repeatmasker.RepeatMaskerCodec.decode(RepeatMaskerCodec.java:17)
        at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.readNextRecord(TribbleIndexedFeatureReader.java:375)
        ... 5 more
"java -Xmx2g $jvm_args -cp $GRIDSS_JAR gridss.repeatmasker.AnnotateVariantsRepeatMasker --INPUT "$input_vcf" --OUTPUT "$output" --REPEAT_MASKER "$rmfile"" command completed with exit code 1.
```
