### ISSUE TITLE
Tumour Vs Normal, no vcf generated and Exception when running gridss.analysis.ReportThresholdCoverage

### ISSUE THREAD

**Issue by BoudSTER** [PapenfussLab/gridss#519]
Hi,

First of all, thank you for this tool! 

I am interested in comparing tumor vs non-tumor cells from a cell triage in myeloma.
I first ran GRIDSS on a tumor and non-tumor sample independently.
GRIDSS generates 2 VCF without any problem :)

Nevertheless when I try to make a "Joint calling" no VCF is generated is it normal ? I must have made a mistake somewhere... I have searched the docs this afternoon but I have the impression that I am applying the recommendations.

Here is my command line: 

gridss \
--reference path_to/ucsc.hg19.fasta \
--output name_sample \
--assembly name_sample.bam \
--threads 20 \
--jar /opt/GRIDSS/gridss-2.5.0.jar \
--workingdir path_to/name_sample \
--jvmheap 25g \
path_to/name_sample_normal.bam \
path_to/name_sample_tumour.bam

Thanking you in advance 

Boudster.

**Comment by BoudSTER** [comment]
After checking it may be due to a version problem. Indeed I used an old singularity that my team had built a long time ago. 

Starting from the docker I created a singularity image with version 2.12.1. 
With the same command line an error occurs: 

Fri Aug 20 15:18:15 CEST 2021: Running  CollectGridssMetricsAndExtractSVReads|samtools  /mnt/isilon_data_nfs/CRUNCH/AUGUSTIN/MM/scratch/data/bam/L2017340/P025-L2017340D05T2_S121_L002.bam
"$timecmd $samtools_sort -n -T $tmp_prefix.namedsorted-tmp -Obam -o $tmp_prefix.namedsorted.bam /dev/stdin" command completed with exit code 1.
*****
The underlying error message can be found in /mnt/isilon_data_nfs/CRUNCH/AUGUSTIN/MM/scratch/results/L201734_n/gridss.full.20210820_151720.hpc-pgfs10.59464.log
*****

In log file : 
13:18:15.782 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/opt/gridss/gridss-2.12.1-gridss-jar-with-dependencies.jar!/com/intel/gkl/native/libgkl_compression.so
[Fri Aug 20 13:18:15 UTC 2021] CollectGridssMetricsAndExtractSVReads MIN_CLIP_LENGTH=5 READ_PAIR_CONCORDANT_PERCENT=0.995 INSERT_SIZE_METRICS=/mnt/isilon_data_nfs/CRUNCH/AUGUSTIN/MM/scratch/results/L201734_n/P025-L2017340D05T2_S121_L002.bam.gridss.working/tmp.P025-L2017340D05T2_S121_L002.bam.insert_size_metrics UNMAPPED_READS=false INCLUDE_DUPLICATES=true SV_OUTPUT=/dev/stdout GRIDSS_PROGRAM=[CollectCigarMetrics, CollectMapqMetrics, CollectTagMetrics, CollectIdsvMetrics, ReportThresholdCoverage] THRESHOLD_COVERAGE=50000 INPUT=/mnt/isilon_data_nfs/CRUNCH/AUGUSTIN/MM/scratch/data/bam/L2017340/P025-L2017340D05T2_S121_L002.bam ASSUME_SORTED=true OUTPUT=/mnt/isilon_data_nfs/CRUNCH/AUGUSTIN/MM/scratch/results/L201734_n/P025-L2017340D05T2_S121_L002.bam.gridss.working/P025-L2017340D05T2_S121_L002.bam FILE_EXTENSION=null PROGRAM=[CollectInsertSizeMetrics] TMP_DIR=[/mnt/isilon_data_nfs/CRUNCH/AUGUSTIN/MM/scratch/results/L201734_n/P025-L2017340D05T2_S121_L002.bam.gridss.working] COMPRESSION_LEVEL=0 REFERENCE_SEQUENCE=/mnt/isilon_data_nfs/CRUNCH/AUGUSTIN/REF/ucsc.hg19.fasta    MIN_INDEL_SIZE=1 CLIPPED=true INDELS=true SPLIT=true SINGLE_MAPPED_PAIRED=true DISCORDANT_READ_PAIRS=true STOP_AFTER=0 METRIC_ACCUMULATION_LEVEL=[ALL_READS] INCLUDE_UNPAIRED=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Fri Aug 20 13:18:15 UTC 2021] Executing as augustin.boudry2@hpc-pgfs10 on Linux 5.4.89-1.el7.elrepo.x86_64 amd64; OpenJDK 64-Bit Server VM 11.0.11+9-Ubuntu-0ubuntu2.20.04; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.12.1-gridss
INFO	2021-08-20 13:18:16	SAMFileWriterFactory	Unknown file extension, assuming BAM format when writing file: file:///dev/stdout
[Fri Aug 20 13:18:18 UTC 2021] gridss.CollectGridssMetricsAndExtractSVReads done. Elapsed time: 0.04 minutes.
Runtime.totalMemory()=2149580800
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Exception when running gridss.analysis.ReportThresholdCoverage
	at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:253)
	at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:134)
	at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:126)
	at picard.analysis.CollectMultipleMetrics.doWork(CollectMultipleMetrics.java:598)
	at gridss.analysis.CollectGridssMetrics.doWork(CollectGridssMetrics.java:80)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
	at picard.cmdline.CommandLineProgram.instanceMainWithExit(CommandLineProgram.java:196)
	at gridss.CollectGridssMetricsAndExtractSVReads.main(CollectGridssMetricsAndExtractSVReads.java:56)
Caused by: java.lang.RuntimeException: Exception when running gridss.analysis.ReportThresholdCoverage
	at picard.analysis.SinglePassSamProgram.raiseAsyncException(SinglePassSamProgram.java:282)
	at picard.analysis.SinglePassSamProgram.asyncAcceptRead(SinglePassSamProgram.java:273)
	at picard.analysis.SinglePassSamProgram.asyncAcceptReads(SinglePassSamProgram.java:263)
	at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:216)
	... 7 more
Caused by: java.lang.NullPointerException
	at htsjdk.samtools.SAMUtils.validateCigar(SAMUtils.java:937)
	at htsjdk.samtools.SAMRecord.validateCigar(SAMRecord.java:1806)
	at htsjdk.samtools.BAMRecord.getCigar(BAMRecord.java:284)
	at htsjdk.samtools.SAMRecord.getAlignmentEnd(SAMRecord.java:607)
	at au.edu.wehi.idsv.PaddedLinearGenomicCoordinate.getEndLinearCoordinate(PaddedLinearGenomicCoordinate.java:132)
	at au.edu.wehi.idsv.SequentialCoverageThreshold.acceptRecord(SequentialCoverageThreshold.java:24)
	at gridss.analysis.ReportThresholdCoverage.acceptRead(ReportThresholdCoverage.java:69)
	at picard.analysis.SinglePassSamProgram$SinglePassSamProgramRunner.run(SinglePassSamProgram.java:320)
	at java.base/java.lang.Thread.run(Thread.java:829)
samtools sort: failed to read header from "/dev/stdin"

**Comment by BoudSTER** [comment]
Hello, 

I found the problem:
- vcf not generated
Due to a version problem I think.

- Exception when running gridss.analysis.ReportThresholdCoverage 
I solved it by correcting my BWA MEM settings, I removed the -a. 

Sorry for the inconvenience ! 

And thanks for your tools! the tumor Vs normal seems to give satisfactory results, just have to play with the filters.

Bye,

BoudSTERRR
