### ISSUE TITLE
Java OutOfMemoryError in the calling step

### ISSUE THREAD

**Issue by kmnip** [PapenfussLab/gridss#525]
Hi,

I keep getting this `java.lang.OutOfMemoryError` (see below) in the `call` step of GRIDSS for joint-calling of single-cell samples.

I have been bumping up the java heap space and lowering the number of threads every time I restart the run. Currently, I am using these settings `gridss -t 1 --jvmheap 1000g` and it is still failing...

Are there any settings that I can use to get around this problem?
Also, I noticed that the GRIDSS pipeline doesn't catch this error at all, as indicated by the final message, `Run complete with 58 warnings and 0 errors.`.

Thanks,
Ka Ming

```
INFO    2021-09-03 12:27:20     AnnotateInsertedSequence        Annotating inserted sequences in /blah/blah/blah/out.vcf.gz.gridss.working/out.vcf.gz.allocated.vcf
INFO    2021-09-03 12:27:20     AnnotateInsertedSequence        Using in-process bwa alignment
INFO    2021-09-03 12:27:20     BwaAligner      Loading bwa mem index image from /blah/blah/blah/ref/hg19/GRCh37-lite.fa.img
[Fri Sep 03 12:49:41 PDT 2021] gridss.AnnotateInsertedSequence done. Elapsed time: 22.35 minutes.
Runtime.totalMemory()=4294967296
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.ArrayList.<init>(ArrayList.java:154)
        at htsjdk.tribble.util.ParsingUtils.split(ParsingUtils.java:199)
        at htsjdk.variant.vcf.AbstractVCFCodec.createGenotypeMap(AbstractVCFCodec.java:775)
        at htsjdk.variant.vcf.AbstractVCFCodec$LazyVCFGenotypesParser.parse(AbstractVCFCodec.java:121)
        at htsjdk.variant.variantcontext.LazyGenotypesContext.decode(LazyGenotypesContext.java:158)
        at htsjdk.variant.vcf.AbstractVCFCodec.parseVCFLine(AbstractVCFCodec.java:454)
        at htsjdk.variant.vcf.AbstractVCFCodec.decodeLine(AbstractVCFCodec.java:384)
        at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:328)
        at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:48)
        at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:70)
        at htsjdk.tribble.AsciiFeatureCodec.decode(AsciiFeatureCodec.java:37)
        at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.readNextRecord(TribbleIndexedFeatureReader.java:375)
        at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.next(TribbleIndexedFeatureReader.java:354)
        at htsjdk.tribble.TribbleIndexedFeatureReader$WFIterator.next(TribbleIndexedFeatureReader.java:315)
        at au.edu.wehi.idsv.util.AutoClosingIterator.next(AutoClosingIterator.java:52)
        at au.edu.wehi.idsv.vcf.InsertedSequenceAnnotator.ensureNext(InsertedSequenceAnnotator.java:151)
        at au.edu.wehi.idsv.vcf.InsertedSequenceAnnotator.hasNext(InsertedSequenceAnnotator.java:126)
        at gridss.AnnotateInsertedSequence.saveVcf(AnnotateInsertedSequence.java:169)
        at gridss.AnnotateInsertedSequence.doWork(AnnotateInsertedSequence.java:136)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at gridss.AnnotateInsertedSequence.main(AnnotateInsertedSequence.java:66)
Fri Sep  3 12:49:43 PDT 2021: Complete calling  /blah/blah/blah/out.vcf.gz
Fri Sep  3 12:49:43 PDT 2021: Run complete with 58 warnings and 0 errors.
```

**Comment by d-cameron** [comment]
The error message indicates that the variant calling itself actually completed successfully, but it's the post-calling variant annotation that's failing (`gridss.AnnotateInsertedSequence`).

> Runtime.totalMemory()=4294967296

That particular call is controlled by the `--otherjvmheap` parameter, not the `--jvmheap` so it's still only requesting 4Gb for that step. Increase the `--otherjvmheap` memory and you should be fine.

If data restrictions allow, please share the problematic VCF (cameron.d   wehi.edu.au) so I can see why it's using more memory than usual.

**Comment by kmnip** [comment]
Thank you! That solves the problem.
