### ISSUE TITLE
htsjdk.samtools.util.SequenceUtil$SequenceListsDifferException

### ISSUE THREAD

**Issue by jamesdalg** [PapenfussLab/gridss#546]
I'm having some issues running GRIDSS on our cluster(https://hpc.nih.gov/apps/gridss.html). We're using the newest version (just updated today), but I'm encountering a java error I can't make sense of. Is this something to do with samtools, picard, or the java version we're using? What version of each did you build this on?
```
bash-4.2$ gridss -r hg38.fa \
>                   -o gridss_PAUTWB_N_output.vcf.gz \
>                   -a /lscratch/${SLURM_JOB_ID}/PAUTWB_N_assembly.bam \
>                   -w /lscratch/${SLURM_JOB_ID} \
>                   -t 32 \
>                   PAUTWB_N.bam
Using working directory "/lscratch/27050932"
Thu Nov 18 17:25:56 EST 2021: Full log file is: /lscratch/27050932/gridss.full.20211118_172556.cn3566.7029.log
Thu Nov 18 17:25:56 EST 2021: Found /usr/bin/time
Thu Nov 18 17:25:56 EST 2021: Using GRIDSS jar /opt/gridss/gridss-2.12.2-gridss-jar-with-dependencies.jar
Thu Nov 18 17:25:56 EST 2021: Using reference genome "hg38.fa"
Thu Nov 18 17:25:56 EST 2021: Using output VCF gridss_PAUTWB_N_output.vcf.gz
Thu Nov 18 17:25:56 EST 2021: Using assembly bam /lscratch/27050932/PAUTWB_N_assembly.bam
Thu Nov 18 17:25:56 EST 2021: WARNING: GRIDSS scales sub-linearly at high thread count. Up to 8 threads is the recommended level of parallelism.
Thu Nov 18 17:25:56 EST 2021: Using 32 worker threads.
Thu Nov 18 17:25:56 EST 2021: Using no blacklist bed. The encode DAC blacklist is recommended for hg19.
Thu Nov 18 17:25:56 EST 2021: Using JVM maximum heap size of 30g for assembly and variant calling.
Thu Nov 18 17:25:56 EST 2021: Using input file PAUTWB_N.bam
Thu Nov 18 17:25:56 EST 2021: Found /usr/bin/Rscript
Thu Nov 18 17:25:56 EST 2021: Found /usr/bin/samtools
Thu Nov 18 17:25:56 EST 2021: Found /usr/bin/java
Thu Nov 18 17:25:56 EST 2021: Found /usr/bin/bwa
Thu Nov 18 17:25:56 EST 2021: samtools version: 1.10+htslib-1.10.2-3
Thu Nov 18 17:25:56 EST 2021: R version: R scripting front-end version 4.1.0 (2021-05-18)
Thu Nov 18 17:25:56 EST 2021: bwa Version: 0.7.17-r1188
Thu Nov 18 17:25:56 EST 2021: time version: GNU time 1.7
Thu Nov 18 17:25:56 EST 2021: bash version: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
Thu Nov 18 17:25:57 EST 2021: java version: openjdk version "11.0.11" 2021-04-20        OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)     OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
Thu Nov 18 17:25:57 EST 2021: Max file handles: 131072
Thu Nov 18 17:25:57 EST 2021: Running GRIDSS steps: setupreference, preprocess, assemble, call,
Thu Nov 18 17:25:57 EST 2021: Start pre-processing      PAUTWB_N.bam
Thu Nov 18 17:25:57 EST 2021: Running   CollectGridssMetrics    PAUTWB_N.bam    first 10000000 records
"$timecmd java -Xmx$otherjvmheap $jvm_args -cp $gridss_jar gridss.analysis.CollectGridssMetrics REFERENCE_SEQUENCE=$reference TMP_DIR=$dir ASSUME_SORTED=true I=$f O=$tmp_prefix THRESHOLD_COVERAGE=$maxcoverage FILE_EXTENSION=null GRIDSS_PROGRAM=null GRIDSS_PROGRAM=CollectIdsvMetrics PROGRAM=null PROGRAM=CollectInsertSizeMetrics STOP_AFTER=$metricsrecords $picardoptions" command completed with exit code 1.
*****
The underlying error message can be found in /lscratch/27050932/gridss.full.20211118_172556.cn3566.7029.log
*****
bash-4.2$ cp *.vcf.gz /data/CCRBioinfo/dalgleishjl/sv_mapping/gridss_purple_linx/
cp: cannot stat ‘*.vcf.gz’: No such file or directory
bash-4.2$
bash-4.2$
bash-4.2$ cat  /lscratch/27050932/gridss.full.20211118_172556.cn3566.7029.log
Thu Nov 18 17:25:56 EST 2021: Full log file is: /lscratch/27050932/gridss.full.20211118_172556.cn3566.7029.log
Thu Nov 18 17:25:56 EST 2021: Found /usr/bin/time
Thu Nov 18 17:25:56 EST 2021: Using GRIDSS jar /opt/gridss/gridss-2.12.2-gridss-jar-with-dependencies.jar
Thu Nov 18 17:25:56 EST 2021: Using reference genome "hg38.fa"
Thu Nov 18 17:25:56 EST 2021: Using output VCF gridss_PAUTWB_N_output.vcf.gz
Thu Nov 18 17:25:56 EST 2021: Using assembly bam /lscratch/27050932/PAUTWB_N_assembly.bam
Thu Nov 18 17:25:56 EST 2021: WARNING: GRIDSS scales sub-linearly at high thread count. Up to 8 threads is the recommended level of parallelism.
Thu Nov 18 17:25:56 EST 2021: Using 32 worker threads.
Thu Nov 18 17:25:56 EST 2021: Using no blacklist bed. The encode DAC blacklist is recommended for hg19.
Thu Nov 18 17:25:56 EST 2021: Using JVM maximum heap size of 30g for assembly and variant calling.
Thu Nov 18 17:25:56 EST 2021: Using input file PAUTWB_N.bam
Thu Nov 18 17:25:56 EST 2021: Found /usr/bin/Rscript
Thu Nov 18 17:25:56 EST 2021: Found /usr/bin/samtools
Thu Nov 18 17:25:56 EST 2021: Found /usr/bin/java
Thu Nov 18 17:25:56 EST 2021: Found /usr/bin/bwa
Thu Nov 18 17:25:56 EST 2021: samtools version: 1.10+htslib-1.10.2-3
Thu Nov 18 17:25:56 EST 2021: R version: R scripting front-end version 4.1.0 (2021-05-18)
Thu Nov 18 17:25:56 EST 2021: bwa Version: 0.7.17-r1188
Thu Nov 18 17:25:56 EST 2021: time version: GNU time 1.7
Thu Nov 18 17:25:56 EST 2021: bash version: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
Thu Nov 18 17:25:57 EST 2021: java version: openjdk version "11.0.11" 2021-04-20        OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)     OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
Thu Nov 18 17:25:57 EST 2021: Max file handles: 131072
Thu Nov 18 17:25:57 EST 2021: Running GRIDSS steps: setupreference, preprocess, assemble, call,
Thu Nov 18 17:25:57 EST 2021: Start pre-processing      PAUTWB_N.bam
Thu Nov 18 17:25:57 EST 2021: Running   CollectGridssMetrics    PAUTWB_N.bam    first 10000000 records
INFO    2021-11-18 22:25:57     Defaults        Found file for property samjdk.reference_fasta: /lscratch/27050932/hg38.fa
INFO    2021-11-18 22:25:57     CollectGridssMetrics

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    CollectGridssMetrics -REFERENCE_SEQUENCE hg38.fa -TMP_DIR /lscratch/27050932/PAUTWB_N.bam.gridss.working -ASSUME_SORTED true -I PAUTWB_N.bam -O /lscratch/27050932/PAUTWB_N.bam.gridss.working/tmp.PAUTWB_N.bam -THRESHOLD_COVERAGE 50000 -FILE_EXTENSION null -GRIDSS_PROGRAM null -GRIDSS_PROGRAM CollectIdsvMetrics -PROGRAM null -PROGRAM CollectInsertSizeMetrics -STOP_AFTER 10000000
**********


22:25:58.118 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/opt/gridss/gridss-2.12.2-gridss-jar-with-dependencies.jar!/com/intel/gkl/native/libgkl_compression.so
[Thu Nov 18 22:25:58 UTC 2021] CollectGridssMetrics GRIDSS_PROGRAM=[CollectIdsvMetrics] THRESHOLD_COVERAGE=50000 INPUT=PAUTWB_N.bam ASSUME_SORTED=true STOP_AFTER=10000000 OUTPUT=/lscratch/27050932/PAUTWB_N.bam.gridss.working/tmp.PAUTWB_N.bam FILE_EXTENSION=null PROGRAM=[CollectInsertSizeMetrics] TMP_DIR=[/lscratch/27050932/PAUTWB_N.bam.gridss.working] REFERENCE_SEQUENCE=hg38.fa    METRIC_ACCUMULATION_LEVEL=[ALL_READS] INCLUDE_UNPAIRED=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Thu Nov 18 22:25:58 UTC 2021] Executing as dalgleishjl@cn3566 on Linux 3.10.0-862.14.4.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 11.0.11+9-Ubuntu-0ubuntu2.20.04; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.12.2-gridss
ERROR   2021-11-18 22:25:58     ReferenceCommandLineProgram     Reference genome used by PAUTWB_N.bam does not match reference genome hg38.fa. The reference supplied must match the reference used for every input.
[Thu Nov 18 22:25:58 UTC 2021] gridss.analysis.CollectGridssMetrics done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=2149580800
Exception in thread "main" htsjdk.samtools.util.SequenceUtil$SequenceListsDifferException: In files /lscratch/27050932/PAUTWB_N.bam and /lscratch/27050932/hg38.fa
        at htsjdk.samtools.util.SequenceUtil.assertSequenceDictionariesEqual(SequenceUtil.java:345)
        at gridss.cmdline.ReferenceCommandLineProgram.ensureDictionaryMatches(ReferenceCommandLineProgram.java:117)
        at gridss.analysis.CollectGridssMetrics.doWork(CollectGridssMetrics.java:75)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at picard.cmdline.CommandLineProgram.instanceMainWithExit(CommandLineProgram.java:196)
        at gridss.analysis.CollectGridssMetrics.main(CollectGridssMetrics.java:57)
Caused by: htsjdk.samtools.util.SequenceUtil$SequenceListsDifferException: Sequence dictionaries are not the same size (2779, 455)
        at htsjdk.samtools.util.SequenceUtil.assertSequenceListsEqual(SequenceUtil.java:251)
        at htsjdk.samtools.util.SequenceUtil.assertSequenceDictionariesEqual(SequenceUtil.java:334)
        at htsjdk.samtools.util.SequenceUtil.assertSequenceDictionariesEqual(SequenceUtil.java:320)
        at htsjdk.samtools.util.SequenceUtil.assertSequenceDictionariesEqual(SequenceUtil.java:343)
        ... 5 more

```

**Comment by d-cameron** [comment]
>Sequence dictionaries are not the same size (2779, 455)

The reference genome `.fa` file you give to GRIDSS must be the same one as you used to align the input bam. You didn't align with `hg38.fa` so you can call variants against `hg38.fa`.

>Thu Nov 18 17:25:56 EST 2021: WARNING: GRIDSS scales sub-linearly at high thread count. Up to 8 threads is the recommended level of parallelism.
>Thu Nov 18 17:25:56 EST 2021: Using 32 worker threads.
>Thu Nov 18 17:25:56 EST 2021: Using JVM maximum heap size of 30g for assembly and variant calling.

This will results in out of memory errors. If you want to scale GRIDSS above 8 cores, use multiple processes. See https://github.com/PapenfussLab/gridss#how-do-i-perform-assembly-on-multiple-nodes for details.

**Comment by jamesdalg** [comment]
I adjusted the memory, but I think that's not quite the answer.
Looking at the header of the bam:
`@RG     ID:PAUTWB_T     LB:WGS  PU:1    SM:PAUTWB_T     PL:Illumina
@PG     ID: Hash Table Build    VN: 01.003.044.3.8.4-hv-8       CL: dragen --build-hash-table true --ht-reference /is2/projects/CCR-SF/active/RefGenomes/hg38_SEQC/hg38.fa --ht-num-threads 56 --enable-cnv true --output-directory hg38_Altaware_cnv_rna_for_graphmap_v3.8.5 --ht-build-rna-hashtable true --ht-alt-liftover /opt/edico/liftover/bwa-kit_hs38DH_liftover.sam --ht-pop-alt-contigs pop_altContig.fa.gz --ht-pop-alt-liftover pop_liftover.sam.gz --ht-pop-snps pop_snps.vcf.gz        DS: digest_type: 1 digest: 0x5C3D5599 ref_digest: 0x5C6D6C53 ref_index_digest: 0x645A5E37 hash_digest: 0x61598086
`

If you look within, it was aligned to hg38.fa, so I'm not quite sure that's it. Perhaps there's something else I can try. I'm willing ot try anything.

**Comment by d-cameron** [comment]
> it was aligned to hg38.fa
> `/is2/projects/CCR-SF/active/RefGenomes/hg38_SEQC/hg38.fa`
> `/opt/edico/liftover/bwa-kit_hs38DH_liftover.sam`

These are different reference genomes. hg38 has 455 contigs, whereas the other one you used has 2779 contigs. That reference is also different to hs38DH which has 3366 contigs.

The reference genome .fa file you give to GRIDSS must exactly match the reference genome specified in the SAM header of the input file. Note that if you've actually done a liftover of some sort then that input bam will probably unusable by GRIDSS. GRIDSS required the chromosome names in the `SA` tag to be correct and I'm not aware of any liftover tool that correctly rewrites the `SA` SAM tag.
