### ISSUE TITLE
Missing `$picardoptions` argument to `gridss.IdentifyVariants`

### ISSUE THREAD

**Issue by lkhilton** [PapenfussLab/gridss#551]
This is a small bug report. I've had several samples fail at this stage of the GRIDSS2 pipeline because of a formatting error in the bam header. All the previous steps run to completion because they receive the `$picardoptions` flag and I have `VALIDATION_STRINGENCY=SILENT` passed to the script. The error in the gridss log file is as follows: 

```
[Thu Dec 02 23:40:05 PST 2021] gridss.IdentifyVariants done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=2147483648
Exception in thread "main" htsjdk.samtools.SAMFormatException: Error parsing SAM header. Problem parsing @PG key:value pair. Line:
@PG	ID:0.1	VN:	CL:bwa aln; bwa sampe ; File /projects/rmorin/projects/gambl-repos/gambl-mutect2-lhilton/results/gambl/gridss-2.0/00-inputs/bam/genome--grch37/14-35632T.bam; Line number 91
	at htsjdk.samtools.SAMTextHeaderCodec.reportErrorParsingLine(SAMTextHeaderCodec.java:258)
	at htsjdk.samtools.SAMTextHeaderCodec.access$200(SAMTextHeaderCodec.java:46)
	at htsjdk.samtools.SAMTextHeaderCodec$ParsedHeaderLine.<init>(SAMTextHeaderCodec.java:307)
	at htsjdk.samtools.SAMTextHeaderCodec.decode(SAMTextHeaderCodec.java:97)
	at htsjdk.samtools.BAMFileReader.readHeader(BAMFileReader.java:707)
	at htsjdk.samtools.BAMFileReader.<init>(BAMFileReader.java:299)
	at htsjdk.samtools.BAMFileReader.<init>(BAMFileReader.java:177)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:396)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:208)
	at gridss.cmdline.ReferenceCommandLineProgram.ensureDictionaryMatches(ReferenceCommandLineProgram.java:108)
	at gridss.cmdline.ReferenceCommandLineProgram.ensureDictionaryMatches(ReferenceCommandLineProgram.java:103)
	at gridss.cmdline.MultipleSamFileCommandLineProgram.ensureDictionariesMatch(MultipleSamFileCommandLineProgram.java:142)
	at gridss.cmdline.MultipleSamFileCommandLineProgram.doWork(MultipleSamFileCommandLineProgram.java:168)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
	at gridss.IdentifyVariants.main(IdentifyVariants.java:26)
```

I updated the `gridss` shell script as follows: 

```
write_status "Running	IdentifyVariants	$output_vcf"
		{ $timecmd java -Xmx$jvmheap $jvm_args \
				-Dgridss.output_to_temp_file=true \
				-cp $gridss_jar gridss.IdentifyVariants \
				TMP_DIR=$workingdir \
				WORKING_DIR=$workingdir \
				REFERENCE_SEQUENCE=$reference \
				WORKER_THREADS=$threads \
				$input_args \
				$blacklist_arg \
				$config_args \
				$assembly_args \
				OUTPUT_VCF=$prefix.unallocated.vcf \
				$readpairing_args \
				$picardoptions \ # Add this to pass VALIDATION_STRINGENCY parameter to this step
```

I can confirm that this fixes the issue and GRIDSS now completes. From what I can tell this is the only GRIDSS sub-command that doesn't get passed the `$picardoptions` flags in the current version.

**Comment by d-cameron** [comment]
Thanks for the bug report :)
