### ISSUE TITLE
Unable to load fermi-lite native library /libbwa.Linux.so

### ISSUE THREAD

**Issue by santoshatanur** [PapenfussLab/gridss#553]
Hi 

I have installed gridss via conda. I am getting the following error when I run gridss. Could you let me know how to fix it.

WARNING 2021-12-12 09:48:35     BwaAligner      Found bwa index files. Attempting to create image from bwa index files
ERROR   2021-12-12 09:48:36     PrepareReference
java.lang.IllegalStateException: Misconfiguration: Unable to load fermi-lite native library /libbwa.Linux.so
        at org.broadinstitute.hellbender.utils.bwa.BwaMemIndex.loadNativeLibrary(BwaMemIndex.java:470)
        at org.broadinstitute.hellbender.utils.bwa.BwaMemIndex.createIndexImageFromIndexFiles(BwaMemIndex.java:121)
        at au.edu.wehi.idsv.alignment.BwaAligner.createBwaIndexFor(BwaAligner.java:69)
        at gridss.PrepareReference.doWork(PrepareReference.java:61)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at gridss.PrepareReference.main(PrepareReference.java:89)
Caused by: java.io.IOException: No such file or directory
        at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.base/java.io.File.createTempFile(File.java:2090)
        at java.base/java.io.File.createTempFile(File.java:2136)
        at org.broadinstitute.hellbender.utils.bwa.BwaMemIndex.loadNativeLibrary(BwaMemIndex.java:464)
        ... 5 more

**Comment by d-cameron** [comment]
What OS/CPU are you using?

**Comment by santoshatanur** [comment]
Linux HPC cluster with multiple nodes. Each node with 12 processor and 96gb memory.
________________________________

**Comment by d-cameron** [comment]
do you have write access to your `java.io.tmpdir` location?

**Comment by santoshatanur** [comment]
No
________________________________

**Comment by d-cameron** [comment]
That'll be the issue. Set you temporary file location environment variable
to a writable location.
