### ISSUE TITLE
AsyncBufferedIterator   Thread interrupt received whilst closing underlying iterator

### ISSUE THREAD

**Issue by YingYa** [PapenfussLab/gridss#555]
Hello,

I am running gridss-2.13.1for paired tumor-normal samples: CRAM files were mapped to Homo_sapiens_assembly38.fasta  (with all ALT contigs).

Does the WARNINGs (--steps call) and ERRORs to ignore, or to investigate further, as it may influence the results?

**********    IdentifyVariants -TMP_DIR /workingdir -WORKING_DIR /workingdir -REFERENCE_SEQUENCE /referencedir/Homo_sapiens_assembly38.fasta -WORKER_THREADS 8 -INPUT ......
............
............
INFO    2022-01-12 13:01:36     VariantCaller   Start calling maximal cliques in chunk 42 (chr1:105000001-chr1:107500000)
**WARNING** 2022-01-12 13:01:36     AsyncBufferedIterator   Thread interrupt received whilst closing underlying iterator
............
............
INFO    2022-01-12 13:08:45     VariantCaller   Start calling maximal cliques in chunk 1003 (chr17:12914949-chr17:15414948)
Ignoring SAM validation error: **ERROR**::INVALID_FLAG_SUPPLEMENTARY_ALIGNMENT:Record 67080, Read name DP8400008282TRL1C037R0490754668, Supplementary alignment flag should not be set for unmapped read.
............
............
[Wed Jan 12 13:16:09 UTC 2022] gridss.IdentifyVariants done. Elapsed time: 15.09 minutes.
Runtime.totalMemory()=4982833152
Wed Jan 12 21:16:10 CST 2022: Running   AnnotateVariants        /workingdir/Tumor.gridss.driver.vcf.gz
INFO    2022-01-12 13:16:10     Defaults        Found file for property samjdk.reference_fasta: /referencedir/Homo_sapiens_assembly38.fasta
INFO    2022-01-12 13:16:10     AnnotateVariants
............
............
INFO    2022-01-12 14:59:49     SequentialCoverageAnnotator     Processed   910,000,000 records.  Elapsed time: 01:43:30s.  Time for last 10,000,000:   78s.  Last read position: chr7:153,759,073
Ignoring SAM validation error: **ERROR**::INVALID_FLAG_SUPPLEMENTARY_ALIGNMENT:Record 43265090, Read name DP8400008282TRL1C015R0420728587, Supplementary alignment flag should not be set for unmapped read.
............
............
INFO    2022-01-12 16:55:27     SequentialCoverageAnnotator     Processed 1,890,000,000 records.  Elapsed time: 03:39:09s.  Time for last 10,000,000:   97s.  Last read position: chrUn_GL000219v1:11
5,799
WARNING 2022-01-12 16:56:31     ReferenceSource Sequence not found: 1_KI270766v1_alt
WARNING 2022-01-12 16:56:31     AsyncBufferedIterator   Thread interrupt received whilst closing underlying iterator
Exception in thread "Normal.realn.cram-Coverage" java.lang.RuntimeException: java.lang.IllegalArgumentException: A reference must be supplied (reference sequence SAMSequenceRecord(name=chr1_KI270766v1_alt,length=256271,dict_index=195,assembly=null) not found).
        at au.edu.wehi.idsv.util.AsyncBufferedIterator$ReaderRunnable.run(AsyncBufferedIterator.java:189)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: A reference must be supplied (reference sequence SAMSequenceRecord(name=chr1_KI270766v1_alt,length=256271,dict_index=195,assembly=null) not found).
        at htsjdk.samtools.cram.build.CRAMReferenceRegion.getReferenceBases(CRAMReferenceRegion.java:77)
        at htsjdk.samtools.cram.structure.Slice.normalizeCRAMRecords(Slice.java:450)
        at htsjdk.samtools.cram.structure.Container.getSAMRecords(Container.java:322)
        at htsjdk.samtools.CRAMIterator.nextContainer(CRAMIterator.java:112)
        at htsjdk.samtools.CRAMIterator.hasNext(CRAMIterator.java:204)
        at htsjdk.samtools.SamReader$AssertingIterator.hasNext(SamReader.java:591)
        at au.edu.wehi.idsv.util.AsyncBufferedIterator$ReaderRunnable.run(AsyncBufferedIterator.java:165)
        ... 1 more
INFO    2022-01-12 16:56:31     VcfTransformCommandLineProgram  Annotated variants written to /workingdir/Tumor.gridss.driver.vcf.gz.gridss.working/Tumor.gridss.driver.vcf.gz.allocated.vcf
[Wed Jan 12 16:56:31 UTC 2022] gridss.AnnotateVariants done. Elapsed time: 220.34 minutes.
............
............

**Comment by d-cameron** [comment]
> Ignoring SAM validation error: ERROR::INVALID_FLAG_SUPPLEMENTARY_ALIGNMENT:Record 43265090, Read name DP8400008282TRL1C015R0420728587, Supplementary alignment flag should not be set for unmapped read.

This indicates an issue with the input file. It doesn't make sense for a read to have both unmapped and supplementary alignment. Not problematic as the GRIDSS coverage step ignores unmapped reads anyway.

> Exception in thread "Normal.realn.cram-Coverage" java.lang.RuntimeException: java.lang.IllegalArgumentException: A reference must be supplied (reference sequence SAMSequenceRecord(name=chr1_KI270766v1_alt,length=256271,dict_index=195,assembly=null) not found).

I'm quite surprised that this error wasn't thrown at the very start of the GRIDSS run.

> Does the WARNINGs (--steps call) and ERRORs to ignore, or to investigate further, as it may influence the results?

The missing reference sequence error looks bad but I haven't encountered it before. If it is problematic it'll be obvious as you'll either have no reference coverage (`REF` and `REFPAIR` fields of 0 for the normal.realn.cram sample), or no records in the output VCF.

**Comment by d-cameron** [comment]
> WARNING 2022-01-12 16:56:31 AsyncBufferedIterator Thread interrupt received whilst closing underlying iterator

This one is fine, it just means that the foreground thread requested the background thread stop when it was already in the processing of stopping.

**Comment by YingYa** [comment]
1) The reference index file (Homo_sapiens_assembly38.dict) and CRAM files all contains chr1_KI270766v1_alt:
     Tumor.realn.cram  : dict_index=196
     Normal.realn.cram : dict_index=196
     Homo_sapiens_assembly38.dict : dict_index=196
     but errors: dict_index=195

2) There are records in the output VCF. BEALN INFO of some records contains chr1_KI270766v1_alt, the REF and REFPAIR fields of these records was not 0 for the normal.realn.cram sample.

**Comment by d-cameron** [comment]
Can you reproduce the error on a tiny bam? It's an error that I haven't seen before.

**Comment by YingYa** [comment]
How to save the intermediate file /workingdir/Tumor.gridss.driver.vcf.gz.gridss.working/Tumor.gridss.driver.vcf.gz.unallocated.vcf ?
Maybe the cotig order not the same with reference index.
