### ISSUE TITLE
Error when executing gridss.CollectGridssMetricsAndExtractSVReads

### ISSUE THREAD

**Issue by Ismail-Curie** [PapenfussLab/gridss#557]
Hello,
Could you please help me resolve this error

12:08:07.899 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/ismail/Tools/gridss-2.13.1/gridss-2.13.1-gridss-jar-with-dependencies.jar!/com/intel/gkl/native/libgkl_compression.so
[Tue Jan 25 12:08:07 CET 2022] CollectGridssMetricsAndExtractSVReads MIN_CLIP_LENGTH=5 READ_PAIR_CONCORDANT_PERCENT=0.995 INSERT_SIZE_METRICS=/media/ismail/Transcend/HPV_short_reads/gridss/case22_wgs_hg19_HPV16.sorted.bam.gridss.working/tmp.case22_wgs_hg19_HPV16.sorted.bam.insert_size_metrics UNMAPPED_READS=false INCLUDE_DUPLICATES=true SV_OUTPUT=/dev/stdout GRIDSS_PROGRAM=[CollectCigarMetrics, CollectMapqMetrics, CollectTagMetrics, CollectIdsvMetrics, ReportThresholdCoverage] THRESHOLD_COVERAGE=50000 INPUT=/media/ismail/Transcend/HPV_short_reads/bwa_wgs/case22_wgs_hg19_HPV16.sorted.bam ASSUME_SORTED=true OUTPUT=/media/ismail/Transcend/HPV_short_reads/gridss/case22_wgs_hg19_HPV16.sorted.bam.gridss.working/case22_wgs_hg19_HPV16.sorted.bam FILE_EXTENSION=null PROGRAM=[CollectInsertSizeMetrics] TMP_DIR=[/media/ismail/Transcend/HPV_short_reads/gridss/case22_wgs_hg19_HPV16.sorted.bam.gridss.working] COMPRESSION_LEVEL=0 REFERENCE_SEQUENCE=/home/ismail/HPV_short_reads/ref/hg19_HPV16.fa    MIN_INDEL_SIZE=1 CLIPPED=true INDELS=true SPLIT=true SINGLE_MAPPED_PAIRED=true DISCORDANT_READ_PAIRS=true STOP_AFTER=0 METRIC_ACCUMULATION_LEVEL=[ALL_READS] INCLUDE_UNPAIRED=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Tue Jan 25 12:08:07 CET 2022] Executing as ismail@BioinfoLondono on Linux 5.4.0-94-generic amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_251-b08; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.13.1-gridss
INFO	2022-01-25 12:08:08	SAMFileWriterFactory	Unknown file extension, assuming BAM format when writing file: file:///dev/stdout
[Tue Jan 25 12:08:10 CET 2022] gridss.CollectGridssMetricsAndExtractSVReads done. Elapsed time: 0.05 minutes.
Runtime.totalMemory()=1270349824
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Exception when running gridss.cmdline.ByReadNameSinglePassSamProgram$WrappedSinglePassSamProgram
	at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:253)
	at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:134)
	at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:126)
	at picard.analysis.CollectMultipleMetrics.doWork(CollectMultipleMetrics.java:598)
	at gridss.analysis.CollectGridssMetrics.doWork(CollectGridssMetrics.java:80)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
	at picard.cmdline.CommandLineProgram.instanceMainWithExit(CommandLineProgram.java:196)
	at gridss.CollectGridssMetricsAndExtractSVReads.main(CollectGridssMetricsAndExtractSVReads.java:56)
Caused by: java.lang.RuntimeException: Exception when running gridss.cmdline.ByReadNameSinglePassSamProgram$WrappedSinglePassSamProgram
	at picard.analysis.SinglePassSamProgram.raiseAsyncException(SinglePassSamProgram.java:282)
	at picard.analysis.SinglePassSamProgram.asyncAcceptRead(SinglePassSamProgram.java:273)
	at picard.analysis.SinglePassSamProgram.asyncAcceptReads(SinglePassSamProgram.java:263)
	at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:216)
	... 7 more
Caused by: htsjdk.samtools.util.RuntimeIOException: Write error; BinaryCodec in writemode; streamed file (filename not available)
	at htsjdk.samtools.util.BinaryCodec.writeBytes(BinaryCodec.java:222)
	at htsjdk.samtools.util.BlockCompressedOutputStream.writeGzipBlock(BlockCompressedOutputStream.java:451)
	at htsjdk.samtools.util.BlockCompressedOutputStream.deflateBlock(BlockCompressedOutputStream.java:415)
	at htsjdk.samtools.util.BlockCompressedOutputStream.write(BlockCompressedOutputStream.java:305)
	at htsjdk.samtools.util.BinaryCodec.writeBytes(BinaryCodec.java:220)
	at htsjdk.samtools.util.BinaryCodec.writeBytes(BinaryCodec.java:212)
	at htsjdk.samtools.BAMRecordCodec.encode(BAMRecordCodec.java:168)
	at htsjdk.samtools.BAMFileWriter.writeAlignment(BAMFileWriter.java:144)
	at htsjdk.samtools.SAMFileWriterImpl.addAlignment(SAMFileWriterImpl.java:185)
	at htsjdk.samtools.AsyncSAMFileWriter.synchronouslyWrite(AsyncSAMFileWriter.java:36)
	at htsjdk.samtools.AsyncSAMFileWriter.synchronouslyWrite(AsyncSAMFileWriter.java:16)
	at htsjdk.samtools.util.AbstractAsyncWriter$WriterRunnable.run(AbstractAsyncWriter.java:123)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:60)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:211)
	at java.nio.channels.Channels.writeFullyImpl(Channels.java:78)
	at java.nio.channels.Channels.writeFully(Channels.java:101)
	at java.nio.channels.Channels.access$000(Channels.java:61)
	at java.nio.channels.Channels$1.write(Channels.java:174)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
	at htsjdk.samtools.util.BinaryCodec.writeBytes(BinaryCodec.java:220)
	... 12 more

This is my command
/home/ismail/Tools/gridss-2.13.1/gridss \
--skipsoftcliprealignment \
--jvmheap 50g \
--reference /home/ismail/HPV_short_reads/ref/hg19_HPV16.fa \
--output /media/ismail/Transcend/HPV_short_reads/gridss/case22_wgs.vcf.gz \
--assembly /media/ismail/Transcend/HPV_short_reads/gridss/case22/assembly.bam \
--threads 8 \
--jar /home/ismail/Tools/gridss-2.13.1/gridss-2.13.1-gridss-jar-with-dependencies.jar \
--workingdir /media/ismail/Transcend/HPV_short_reads/gridss \
--blacklist /home/ismail/Tools/gridss/example/ENCFF001TDO.bed \
--steps All \
/media/ismail/Transcend/HPV_short_reads/bwa_wgs/case22_wgs_hg19_HPV16.sorted.bam

Thank you,
Ismail

**Comment by d-cameron** [comment]
> Caused by: htsjdk.samtools.util.RuntimeIOException: Write error; BinaryCodec in writemode; streamed file (filename not available)

That's Java's very very verbose way of saying `Broken Pipe`. The actual error is going to from the `samtools sort` that `gridss.CollectGridssMetricsAndExtractSVReads` pipes it's output to. Unfortunately, you haven't included that. Usually these samtools crashes are because you ran out of memory or disk space, although I have seen `Segmentation Fault` for specific versions of samtools.

**Comment by Ismail-Curie** [comment]
Thnak you @d-cameron.
