### ISSUE TITLE
virus breakend error

### ISSUE THREAD

**Issue by shashank-bgp** [PapenfussLab/gridss#565]
I am getting following error:

Thu Feb 17 07:53:17 UTC 2022: Identifying viral sequences
Thu Feb 17 07:53:18 UTC 2022: Treating 0 reference sequences as viral sequences.
Thu Feb 17 07:53:58 UTC 2022: Identifying viral taxa in sample based on kraken2 summary report
Thu Feb 17 07:54:08 UTC 2022: Exit status 0 for $timecmd java -Xmx8g $jvm_args -cp $gridss_jar gridss.kraken.IdentifyViralTaxa --INPUT_KRAKEN2_REPORT $file_report --OUTPUT $file_summary_taxa_tsv --REPORT_OUTPUT $file_viral_report --SUMMARY_REPORT_OUTPUT $file_extracted_report --NCBI_NODES_DMP $nodesdmp --SEQID2TAXID_MAP $seqidtaxidmap --MIN_SUPPORTING_READS $minreads --TAXONOMIC_DEDUPLICATION_LEVEL Genus $taxid_args 1>&2 2>> $logfile
*****
*****
See log file ./SRR5090597.virusbreakend.vcf.virusbreakend.working/virusbreakend.20220217_075317.ip-172-21-10-139.4572.log for underlying error
*****
*****

Runtime.totalMemory()=2405433344
Exception in thread "main" java.lang.NullPointerException
        at gridss.kraken.IdentifyViralTaxa.createSummaryLine(IdentifyViralTaxa.java:182)
        at gridss.kraken.IdentifyViralTaxa.lambda$doWork$11(IdentifyViralTaxa.java:153)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at gridss.kraken.IdentifyViralTaxa.doWork(IdentifyViralTaxa.java:154)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at gridss.kraken.IdentifyViralTaxa.main(IdentifyViralTaxa.java:221)

Please help me rectify the error.

**Comment by alexjfortuna** [comment]
I am having the same issue. Did you ever have any luck?
