### ISSUE TITLE
ExtractSVReads writing disordered records

### ISSUE THREAD

**Issue by jbedo** [PapenfussLab/gridss#573]
ExtractSVReads is crashing when writing the output as the order is inconsistent:

```
INFO    2022-03-31 03:26:01     ExtractSVReads

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    ExtractSVReads -VERBOSITY WARNING -REFERENCE_SEQUENCE ref.fa -I input.bam -O /nix/store/qsf3gypdw8ld8ni12lz2djd3m2ykicqh-bionix-gridss-extractSVReads -UNMAPPED_READS false -MIN_CLIP_LENGTH 5
**********


03:26:05.224 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/nix/store/sww42m4als84g39f2db2lwspq4dddmqb-gridss-2.13.2-gridss-jar-with-dependencies.jar!/com/intel/gkl/native/libgkl_compression.so
[Thu Mar 31 03:26:05 UTC 2022] ExtractSVReads MIN_CLIP_LENGTH=5 UNMAPPED_READS=false INPUT=input.bam OUTPUT=/nix/store/qsf3gypdw8ld8ni12lz2djd3m2ykicqh-bionix-gridss-extractSVReads VERBOSITY=WARNING REFERENCE_SEQUENCE=ref.fa    MIN_INDEL_SIZE=1 CLIPPED=true INDELS=true SPLIT=true SINGLE_MAPPED_PAIRED=true DISCORDANT_READ_PAIRS=true INCLUDE_DUPLICATES=false ASSUME_SORTED=true STOP_AFTER=0 IGNORE_DUPLICATES=true QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=true CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Thu Mar 31 03:26:05 UTC 2022] Executing as ?@milton-sml-003.hpc.wehi.edu.au on Linux 3.10.0-1160.42.2.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 17.0.1+12-nixos; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.13.2-gridss
[Thu Mar 31 03:26:06 UTC 2022] gridss.ExtractSVReads done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=243269632
Exception in thread "main" java.lang.IllegalArgumentException: Alignments added out of order in SAMFileWriterImpl.addAlignment for file:///nix/store/qsf3gypdw8ld8ni12lz2djd3m2ykicqh-bionix-gridss-extractSVReads. Sort order is queryname. Offending records are at [700666F:260:CA8M4ANXX:1:1101:1005:6273] and [700666F:260:CA8M4ANXX:1:1101:1005:22831]
        at htsjdk.samtools.SAMFileWriterImpl.assertPresorted(SAMFileWriterImpl.java:197)
        at htsjdk.samtools.SAMFileWriterImpl.addAlignment(SAMFileWriterImpl.java:184)
        at gridss.ExtractSVReads.acceptFragment(ExtractSVReads.java:174)
        at gridss.cmdline.ByReadNameSinglePassSamProgram.makeItSo(ByReadNameSinglePassSamProgram.java:107)
        at gridss.cmdline.ByReadNameSinglePassSamProgram.doWork(ByReadNameSinglePassSamProgram.java:51)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at gridss.ExtractSVReads.main(ExtractSVReads.java:153)
﻿```


GRIDSS 2.13.2

**Comment by d-cameron** [comment]
What's the driver for this? The default `gridss` driver has `ASSUME_SORTED=true` (https://github.com/PapenfussLab/gridss/blob/master/scripts/gridss#L778) since the output order doesn't matter (since it gets immediately piped to `samtool sort`) and the subsequent `ComputeSamTags` step also has `ASSUME_SORTED=true` since samtools sand htsjdk disagree on sort ordering.

It sounds like the issue is input file it not sorted as expected and it's dying on the output sorting validation. Is this the case?

**Comment by jbedo** [comment]
This is it, the log above shows `ASSUME_SORTED=true`; it wasn't explicitly specified though:
```
java -Dsamjdk.create_index=true \
  -cp /nix/store/sww42m4als84g39f2db2lwspq4dddmqb-gridss-2.13.2-gridss-jar-with-dependencies.jar gridss.ExtractSVReads \
  VERBOSITY=WARNING \
  REFERENCE_SEQUENCE=ref.fa \
  I=input.bam \
  O=$out \
  UNMAPPED_READS=false \
   \
  MIN_CLIP_LENGTH=5 \
```

Is the `ASSUME_SORTED=true` default expected?
