### ISSUE TITLE
Missing Quality Line at line 1553 in fastq /dev/fd/63

### ISSUE THREAD

**Issue by YingYa** [PapenfussLab/gridss#577]
Hi

extractFragmentsToFastq fail to extract Quality Line for one read from CRAM file.

INFO    2022-04-07 08:09:12     ExtractBestViralReference       Identifying best viral reference genomes from /dev/fd/63
[Thu Apr 07 08:09:12 UTC 2022] gridss.kraken.ExtractBestViralReference done. Elapsed time: 0.38 minutes.
Runtime.totalMemory()=4343201792
Exception in thread "main" htsjdk.samtools.SAMException: Missing Quality Line at line 1553 in fastq /dev/fd/63
        at htsjdk.samtools.fastq.FastqReader.checkLine(FastqReader.java:190)
        at htsjdk.samtools.fastq.FastqReader.readNextRecord(FastqReader.java:126)
        at htsjdk.samtools.fastq.FastqReader.next(FastqReader.java:152)
        at gridss.kraken.ExtractBestViralReference.doWork(ExtractBestViralReference.java:123)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at gridss.kraken.ExtractBestViralReference.main(ExtractBestViralReference.java:257)

I then use the samtools (v1.15) to do the same thing, which could be successfully each Quality Line:
samtools view -h -u -@ 8 -N tumor.virusbreakend.vcf.gz.readnames.txt --reference 
 Homo_sapiens_assembly38.fasta tumor.cram | samtools fastq -@ 8 -1 tumor.R1.fq -2 tumor.R2.fq -s tumor.unpaired.fq -

**Comment by d-cameron** [comment]
Is the underlying CRAM record missing quality score information? Can you post the relevant reads so I can reproduce locally?

**Comment by YingYa** [comment]
No, The underlying CRAM record all quality score information. The relevant reads have been posted:
[test.virusbreakend.vcf.gz.virusbreakend.working.tar.gz](https://github.com/PapenfussLab/gridss/files/8460981/test.virusbreakend.vcf.gz.virusbreakend.working.tar.gz)

**Comment by gavin-peng** [comment]
Hi,
We are seeing same issue in our using virusbreakend:

Exception in thread "main" htsjdk.samtools.SAMException: Missing Quality Line at line 6249 in fastq /dev/fd/63

also I searched in the input bam file, and the read with same identifier does not missing quality line and strangely the sequence also different.
Wondering if there is any progress on this issue.

**Comment by YingYa** [comment]
When we got the issue 'Exception in thread "main" htsjdk.samtools.SAMException: Missing Quality Line at line XXXX in fastq /dev/fd/63', we could manually extract Fragments from BAM/CRAM To Fastq  by other tools, for example:

cd  /path/to/tumor.virusbreakend.vcf.gz.virusbreakend.working
samtools view -h -u -@ 8 -N tumor.virusbreakend.vcf.gz.readnames.txt --reference
/path/to/hg38.fasta /path/to/tumor.cram | samtools fastq -@ 8 -1 tumor.R1.fq -2 tumor.R2.fq -0 tumor.unpaired.fq -

Then rerun the virusbreakend shell. virusbreakend will start from the last breakpoint and use the manually extracted tumor.R1.fq, tumor.R2.fq and tumor.unpaired.fq.

Hope this could be helping.
