### ISSUE TITLE
SingleReadEvidence.getHomologySequence crash point.

### ISSUE THREAD

**Issue by AMChalkie** [PapenfussLab/gridss#60]
Gridss gridss-1.2.4-jar-with-dependencies.jar fails on WES sample with the following error message shown below. Same thing on previous version, so not version dependent. 

More helpful error code would be useful here to know if it is an issue of configuration or otherwise. Happy to run a verbose debugging output if such an option exists.

Cheers
/Alistair

INFO	2017-02-20 13:41:19	SequentialCoverageAnnotator	Processed    16,000,000 records.  Elapsed time: 00:42:36s.  Time for last 1,000,000:    8s.  Last read position: chr2:103,059,573
INFO	2017-02-20 13:41:56	SequentialCoverageAnnotator	Processed    17,000,000 records.  Elapsed time: 00:43:13s.  Time for last 1,000,000:   37s.  Last read position: chr2:135,780,939
INFO	2017-02-20 13:42:03	SequentialCoverageAnnotator	Processed    18,000,000 records.  Elapsed time: 00:43:19s.  Time for last 1,000,000:    6s.  Last read position: chr2:171,819,259
[Mon Feb 20 13:42:04 AEDT 2017] gridss.CallVariants done. Elapsed time: 58.68 minutes.
Runtime.totalMemory()=5926551552
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 45
	at java.lang.String.substring(String.java:1963)
	at au.edu.wehi.idsv.SingleReadEvidence.getHomologySequence(SingleReadEvidence.java:291)
	at au.edu.wehi.idsv.StructuralVariationCallBuilder.make(StructuralVariationCallBuilder.java:303)
	at gridss.AllocateEvidence.annotate(AllocateEvidence.java:127)
	at gridss.AllocateEvidence.lambda$iterator$184(AllocateEvidence.java:79)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:817)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:674)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at au.edu.wehi.idsv.util.AutoClosingIterator.hasNext(AutoClosingIterator.java:48)
	at au.edu.wehi.idsv.SequentialCoverageAnnotator.hasNext(SequentialCoverageAnnotator.java:121)
	at au.edu.wehi.idsv.util.ParallelTransformIterator.dispatch(ParallelTransformIterator.java:101)
	at au.edu.wehi.idsv.util.ParallelTransformIterator.next(ParallelTransformIterator.java:94)
	at au.edu.wehi.idsv.util.AutoClosingIterator.next(AutoClosingIterator.java:53)
	at com.google.common.collect.Iterators$PeekingImpl.peek(Iterators.java:1194)
	at au.edu.wehi.idsv.util.WindowedSortingIterator.nextRecordCouldBeAtStartOfWindow(WindowedSortingIterator.java:83)
	at au.edu.wehi.idsv.util.WindowedSortingIterator.advanceUnderlying(WindowedSortingIterator.java:76)
	at au.edu.wehi.idsv.util.WindowedSortingIterator.computeNext(WindowedSortingIterator.java:62)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.Iterators$PeekingImpl.hasNext(Iterators.java:1171)
	at com.google.common.collect.Iterators$MergingIterator.next(Iterators.java:1326)
	at au.edu.wehi.idsv.util.AutoClosingIterator.next(AutoClosingIterator.java:53)
	at gridss.cmdline.VcfTransformCommandLineProgram.saveVcf(VcfTransformCommandLineProgram.java:80)
	at gridss.cmdline.VcfTransformCommandLineProgram.doWork(VcfTransformCommandLineProgram.java:51)
	at gridss.CallVariants.execute(CallVariants.java:103)
	at gridss.CallVariants.callVariants(CallVariants.java:91)
	at gridss.CallVariants.doWork(CallVariants.java:124)
	at gridss.cmdline.MultipleSamFileCommandLineProgram.doWork(MultipleSamFileCommandLineProgram.java:202)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:208)
	at gridss.CallVariants.main(CallVariants.java:107)

**Comment by d-cameron** [comment]
Thanks for raising the issue. Can you test against version 1.3.0? It shouldn't crash, but it would be helpful if you could add the relevant ERROR level log messages to this issue so I can track down the root cause.

Thanks
Daniel
