### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException:

### ISSUE THREAD

**Issue by jigaoxiang** [PapenfussLab/gridss#600]
Dear Dr：
          When I used the Gridss with the parameter `gridss -r ref.fasta -t 20 --useproperpair -o gridss_output/Sample.vcf.gz Sample.bam`. There are some error happened. Please give some advice for this.

```
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Exception when running gridss.cmdline.ByReadNameSinglePassSamProgram$WrappedSinglePassSamProgram
        at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:253)
        at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:134)
        at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:126)
        at picard.analysis.CollectMultipleMetrics.doWork(CollectMultipleMetrics.java:598)
        at gridss.analysis.CollectGridssMetrics.doWork(CollectGridssMetrics.java:80)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at picard.cmdline.CommandLineProgram.instanceMainWithExit(CommandLineProgram.java:196)
        at gridss.CollectGridssMetricsAndExtractSVReads.main(CollectGridssMetricsAndExtractSVReads.java:56)
Caused by: java.lang.RuntimeException: Exception when running gridss.cmdline.ByReadNameSinglePassSamProgram$WrappedSinglePassSamProgram
        at picard.analysis.SinglePassSamProgram.raiseAsyncException(SinglePassSamProgram.java:282)
        at picard.analysis.SinglePassSamProgram.asyncAcceptRead(SinglePassSamProgram.java:273)
        at picard.analysis.SinglePassSamProgram.asyncAcceptReads(SinglePassSamProgram.java:263)
        at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:216)
        ... 7 more
Caused by: java.lang.NullPointerException
        at htsjdk.samtools.SAMUtils.validateCigar(SAMUtils.java:937)
        at htsjdk.samtools.SAMRecord.validateCigar(SAMRecord.java:1806)
        at htsjdk.samtools.BAMRecord.getCigar(BAMRecord.java:284)
        at gridss.ExtractSVReads.isFullyMapped(ExtractSVReads.java:94)
        at gridss.ExtractSVReads.hasReadAlignmentConsistentWithReference(ExtractSVReads.java:75)
        at gridss.ExtractSVReads.shouldExtract(ExtractSVReads.java:158)
        at gridss.ExtractSVReads.acceptFragment(ExtractSVReads.java:171)
        at gridss.cmdline.ByReadNameSinglePassSamProgram$WrappedSinglePassSamProgram.acceptRead(ByReadNameSinglePassSamProgram.java:162)
        at picard.analysis.SinglePassSamProgram$SinglePassSamProgramRunner.run(SinglePassSamProgram.java:320)
        at java.base/java.lang.Thread.run(Thread.java:834)
[W::bgzf_read_block] EOF marker is absent. The input is probably truncated
samtools sort: truncated file. Aborting

```

**Comment by d-cameron** [comment]
That looks like an input file error. Can you successfully run Picard tools
ValidateSam on your input bam?

**Comment by jigaoxiang** [comment]
> 

Thank you for reply!
At first, I also thought maybe my bam file have some problem. But using the picard check bam file, there is no error on my input bam. So it is confused me long time. There is the check out of `picard ValidateSamFile` my input bam.
```
## HISTOGRAM	java.lang.String
Error Type	Count
WARNING:QUALITY_NOT_STORED	1

[Mon Sep 05 20:20:05 CST 2022] picard.sam.ValidateSamFile done. Elapsed time: 6.33 minutes.
Runtime.totalMemory()=1068498944
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp

```
