### ISSUE TITLE
PositionalAssembler Errors >100 times

### ISSUE THREAD

**Issue by jackieduckie** [PapenfussLab/gridss#601]
Hi Daniel,

GRIDSS failed on one sample with many PositionalAssembler errors. The error message below is one of them. GRIDSS couldn't produce a VCF on this sample.

5659   │ ERROR   2022-10-03 06:10:10 PositionalAssembler Error assembling 1. Please raise an issue at https://github.c
       │ om/PapenfussLab/gridss/issues. If your data can be shared publicly, please also include a minimal data set fo
       │ r reproducing the problem by attaching /data/output/gridss_minimal_reproduction_data_for_error_1.zip.. Attemp
       │ ting recovery by resuming assembly at 1:25099882
5660   │ java.lang.RuntimeException: Sanity check failure: found path with no support (1:24992975)
5661   │     at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.callContig(NonReferenceContigAssemble
       │ r.java:670)
5662   │     at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.flushCallsOutsideRetainWindow(NonRefe
       │ renceContigAssembler.java:230)
5663   │     at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.ensureCalledContig(NonReferenceContig
       │ Assembler.java:260)
5664   │     at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.hasNext(NonReferenceContigAssembler.j
       │ ava:194)
5665   │     at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.flushIfRequired(PositionalAssembler.java:79)
5666   │     at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:292)
5667   │     at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:106)
5668   │     at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.hasNext(PositionalAssembler.java:64)
5669   │     at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:240)
5670   │     at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:197)
5671   │     at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$2(AssemblyEvidenceSource.java:100)
5672   │     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
5673   │     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
5674   │     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
5675   │     at java.lang.Thread.run(Thread.java:748)

The reproduction zip file of this error is attached. 
[gridss_minimal_reproduction_data_for_error_1.zip](https://github.com/PapenfussLab/gridss/files/9711613/gridss_minimal_reproduction_data_for_error_1.zip)

**Comment by alhafidzhamdan** [comment]
Hi @jackieduckie , any chance you've got this solved? I'm encountering the exact same issue.
My sample is aligned using Isaac aligner.
