### ISSUE TITLE
long chromosomes that require .csi index lead to htsjdk error

### ISSUE THREAD

**Issue by jjuod** [PapenfussLab/gridss#602]
Hi, I'm working with long chromosomes (barley) that require .csi indexing instead of .bai. Is this currently supported in gridss?
The specific error that I'm getting is:
```
ERROR   2022-10-14 15:20:31     AssemblyEvidenceSource  Fatal error during assembly 
java.util.concurrent.ExecutionException: htsjdk.samtools.SAMException: Exception when processing alignment for BAM index asm53-20404 161b aligned to contig2:536877234-536877371.
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.runTasks(AssemblyEvidenceSource.java:168)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleBreakends(AssemblyEvidenceSource.java:108)
        at gridss.AssembleBreakends.doWork(AssembleBreakends.java:43)
        at gridss.cmdline.MultipleSamFileCommandLineProgram.doWork(MultipleSamFileCommandLineProgram.java:173)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at gridss.AssembleBreakends.main(AssembleBreakends.java:35)
Caused by: htsjdk.samtools.SAMException: Exception when processing alignment for BAM index asm53-20404 16
1b aligned to contig2:536877234-536877371.                                                                       at htsjdk.samtools.BAMFileWriter.writeAlignment(BAMFileWriter.java:141)
        at htsjdk.samtools.SAMFileWriterImpl.addAlignment(SAMFileWriterImpl.java:185)
        at htsjdk.samtools.AsyncSAMFileWriter.synchronouslyWrite(AsyncSAMFileWriter.java:36)
        at htsjdk.samtools.AsyncSAMFileWriter.synchronouslyWrite(AsyncSAMFileWriter.java:16)
        at htsjdk.samtools.util.AbstractAsyncWriter$WriterRunnable.run(AbstractAsyncWriter.java:123)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: htsjdk.samtools.SAMException: Exception creating BAM index for record asm53-20404 161b aligned
 to contig2:536877234-536877371.                                                                                 at htsjdk.samtools.BAMIndexer.processAlignment(BAMIndexer.java:132)
        at htsjdk.samtools.BAMFileWriter.writeAlignment(BAMFileWriter.java:138)
        ... 5 more
Caused by: java.lang.IllegalStateException: Read position too high for BAI bin indexing.
        at htsjdk.samtools.SAMRecord.computeIndexingBin(SAMRecord.java:1576)
        at htsjdk.samtools.BAMIndexer$BAMIndexBuilder$1.getIndexingBin(BAMIndexer.java:250)
        at htsjdk.samtools.BinningIndexBuilder.processFeature(BinningIndexBuilder.java:96)
        at htsjdk.samtools.BAMIndexer$BAMIndexBuilder.processAlignment(BAMIndexer.java:238)
        at htsjdk.samtools.BAMIndexer.processAlignment(BAMIndexer.java:130)
        ... 6 more
```
Googling I find some more issues with csi support in htsjdk, so not sure if this something that can be fixed within gridss, or is this out of your hands? Thanks!

**Comment by d-cameron** [comment]
I'll look into it further but that is indeed likely to be the case.

**Comment by WimSpee** [comment]
Dear GRIDDs developers, @d-cameron , 

Thank you for the very useful GRIDDS software. We ran into the same issue. 
We found work arounds that we hope could be implement so that GRIDDs out of the box works for everyone working on large genome/chromosome species. 

**1) HTSJDK not being able to index large chromosome BAM file**
The workaround we found for this is to index the intermediate BAM files via `samtools index --csi` and then restarting the GRIDDS analysis. HTSJDK is able to read BAM files indexed via CSI as for example shown by loading large genome/chromosome BAM+CSI files in IGV. 

So maybe the GRIDDS software could be modified to (optionally) make a system call to samtools for CSI indexing the large chromosome intermediate BAM files?

**2) Use LONG values to prevent going over the 32bit INT limit** 
Some species have chromosomes that are close or even over the 32bit INT limit (2,147,483,647). 
Because the 32 bit limit is hard in multiple bio-informatics  software we do tend to split chromosome to be smaller than 2Gb. 

There at least is 1 place in the GRIDDS code where variant start and stop are added to be averaged. This addition can go over the 32bit INT limit with sub 2Gb chromosomes.  To prevent the 32bit overflow LONG values can be used for the addition. 

https://github.com/PapenfussLab/gridss/blob/09900c48d6d0e899a155cbc185f3d8e7c511bf05/src/main/java/au/edu/wehi/idsv/BreakendMaximalEvidenceCliqueIterator.java#L75


```
// Perform the calculation with long and then cast to int
--
long lstart = (long) start;
long lend = (long) end;
int nominal = (int) ((lstart + lend) / 2);
BreakendSummary breakend = new BreakendSummary(referenceIndex, direction, nominal, start, end);
```

Thank you for considering  the implementation of theses changes to make GRIDDS work out of the box for large genome/chromosome species.
