### ISSUE TITLE
gridss call error

### ISSUE THREAD

**Issue by vitty0513** [PapenfussLab/gridss#631]
Dear,
I met a error when I run: gridss -s call --reference $ref -a assembly.bam --output ACB_gridss.vcf --jvmheap 60g --otherjvmheap 60g --jar /home/banliping/WORKSPACE/dwt/software/gridss-2.13.2-gridss-jar-with-dependencies.jar $dir/AH14_MarkDup.bam 

the log is :
[M::process] read 107586 sequences (10000251 bp)...
[M::mem_process_seqs] Processed 107586 reads in 128.060 CPU sec, 77.282 real sec
[M::process] read 109438 sequences (10000015 bp)...
[M::mem_process_seqs] Processed 109438 reads in 130.298 CPU sec, 78.896 real sec
[M::process] read 107308 sequences (10000062 bp)...
[M::mem_process_seqs] Processed 107308 reads in 134.199 CPU sec, 81.460 real sec
[M::process] read 109800 sequences (10000000 bp)...
[M::mem_process_seqs] Processed 109800 reads in 119.501 CPU sec, 72.211 real sec
INFO    2023-06-11 13:44:43     AnnotateInsertedSequence        Processed    17,000,000 records.  Elapsed time: 06:02:54s.  Time for last 1,000,000: 1,206s.  Last read position: LG30:6,448,011
[M::process] read 108234 sequences (10000158 bp)...
[M::mem_process_seqs] Processed 108234 reads in 123.077 CPU sec, 74.206 real sec
[M::process] read 107940 sequences (10000061 bp)...
[M::mem_process_seqs] Processed 107940 reads in 122.843 CPU sec, 74.315 real sec
INFO    2023-06-11 13:53:50     ExternalProcessStreamingAligner Waiting for external aligner to complete all alignments.
[M::process] read 27311 sequences (2554035 bp)...
[M::mem_process_seqs] Processed 27311 reads in 32.186 CPU sec, 19.362 real sec
ERROR   2023-06-11 13:54:50     ExternalProcessHelper   External process still alive: "bwa mem -K 10000000 -L 0,0 -t 8 /home/banliping/WORKSPACE/dwt/ACB/ref/Lachesis_assembly_changed.fa -"
ERROR   2023-06-11 13:54:50     ExternalProcessHelper   Subprocess terminated with with exit status 137. Failed executing "bwa mem -K 10000000 -L 0,0 -t 8 /home/banliping/WORKSPACE/dwt/ACB/ref/Lachesis_assembly_changed.fa -". Can you run the alignment command from the command line? Is the aligner on PATH? Did you build an index with prefix /home/banliping/WORKSPACE/dwt/ACB/ref/Lachesis_assembly_changed.fa?
Exception in thread "feedAligner" java.lang.RuntimeException: Subprocess terminated with with exit status 137. Failed executing "bwa mem -K 10000000 -L 0,0 -t 8 /home/banliping/WORKSPACE/dwt/ACB/ref/Lachesis_assembly_changed.fa -". Can you run the alignment command from the command line? Is the aligner on PATH? Did you build an index with prefix /home/banliping/WORKSPACE/dwt/ACB/ref/Lachesis_assembly_changed.fa?
        at au.edu.wehi.idsv.alignment.ExternalProcessHelper.shutdown(ExternalProcessHelper.java:40)
        at au.edu.wehi.idsv.alignment.ExternalProcessHelper.shutdownAligner(ExternalProcessHelper.java:44)
        at au.edu.wehi.idsv.alignment.ExternalProcessStreamingAligner.flush(ExternalProcessStreamingAligner.java:103)
        at au.edu.wehi.idsv.alignment.StreamingAlignerIterator.flush(StreamingAlignerIterator.java:31)
        at au.edu.wehi.idsv.vcf.InsertedSequenceAnnotator.feedStreamingAligner(InsertedSequenceAnnotator.java:110)
        at au.edu.wehi.idsv.vcf.InsertedSequenceAnnotator.lambda$new$0(InsertedSequenceAnnotator.java:48)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "ExternalProcessStreamingAligner" htsjdk.samtools.util.RuntimeIOException: java.io.IOException: Stream closed
        at htsjdk.samtools.util.BufferedLineReader.readLine(BufferedLineReader.java:70)
        at htsjdk.samtools.SAMTextReader.advanceLine(SAMTextReader.java:221)
        at htsjdk.samtools.SAMTextReader.access$800(SAMTextReader.java:37)
        at htsjdk.samtools.SAMTextReader$RecordIterator.next(SAMTextReader.java:257)
        at htsjdk.samtools.SAMTextReader$RecordIterator.next(SAMTextReader.java:228)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:574)
        at htsjdk.samtools.SamReader$AssertingIterator.next(SamReader.java:553)
        at au.edu.wehi.idsv.alignment.ExternalProcessStreamingAligner.readAllAlignments(ExternalProcessStreamingAligner.java:139)
        at au.edu.wehi.idsv.alignment.ExternalProcessStreamingAligner.lambda$ensureAligner$2(ExternalProcessStreamingAligner.java:77)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Stream closed
        at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:336)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.readLine(BufferedReader.java:324)
        at java.io.LineNumberReader.readLine(LineNumberReader.java:201)
        at htsjdk.samtools.util.BufferedLineReader.readLine(BufferedLineReader.java:68)
        ... 9 more

However I have built an index. How can I solve this error? 

Many thanks

**Comment by vitty0513** [comment]
I have module load BWA/0.7.17 and there're indexes:
Lachesis_assembly_changed.dict
Lachesis_assembly_changed.fa
Lachesis_assembly_changed.fa.amb
Lachesis_assembly_changed.fa.ann
Lachesis_assembly_changed.fa.bwt
Lachesis_assembly_changed.fa.fai
Lachesis_assembly_changed.fa.pac
Lachesis_assembly_changed.fa.sa
 

I don't find anything wrong with my reference genome index and the PATH. It's very strange!

**Comment by d-cameron** [comment]
```
ERROR 2023-06-11 13:54:50 ExternalProcessHelper Subprocess terminated with with exit status 137. Failed executing "bwa mem -K 10000000 -L 0,0 -t 8 /home/banliping/WORKSPACE/dwt/ACB/ref/Lachesis_assembly_changed.fa -". Can you run the alignment command from the command line? Is the aligner on PATH? Did you build an index with prefix
```
What happens when you try to run the quoted command from the command line?
