### ISSUE TITLE
RNA support

### ISSUE THREAD

**Issue by kesner** [PapenfussLab/gridss#654]
Hi,
  Is there support for running this tool on RNA seq datasets.  I tried to run it but it failed.  I guess support would require input of a gtf/gff file of intron/exon boundaries so that these will not be interpreted as structural variants.   Maybe this tool could be made to work as is, but it not clear to me how.  I was hoping to just ignore the intron/exon SVs and look at the rest of the variants.   Our interest is looking at potential Ribozymes modifications which may appear like SVs.  Maybe someone knows of a similar tool that would work?

 

I get many errors like this:
java.lang.RuntimeException: Sanity check failure: found path with no support (chr1:34275184)

and finally this:

   Error assembling chr1. Please raise an issue at https://github.com/PapenfussLab/gridss/issues. If your data can be shared publicly, please also include a minimal data set for reproducing the problem by attaching ./gridss_minimal_reproduction_data_for_error_1.zip.
java.lang.RuntimeException: Sanity check failure: found path with no support (chr1:34275184)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.callContig(NonReferenceContigAssembler.java:673)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.flushCallsOutsideRetainWindow(NonReferenceContigAssembler.java:233)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.ensureCalledContig(NonReferenceContigAssembler.java:263)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.hasNext(NonReferenceContigAssembler.java:197)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.flushIfRequired(PositionalAssembler.java:77)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:298)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:107)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.hasNext(PositionalAssembler.java:62)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:246)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:199)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$2(AssemblyEvidenceSource.java:102)

**Comment by d-cameron** [comment]
RNA-seq is not supported.
