### ISSUE TITLE
hg38 error

### ISSUE THREAD

**Issue by d-cameron** [PapenfussLab/gridss#68]
GRIDSS throws the following error when running on hg38

```
ERROR	2017-02-28 15:57:23	PositionalAssembler	Error assembling chrUn_JTFH01001974v1_decoy. This should not happen. Please raise an issue at https://github.com/PapenfussLab/gridss/issues
java.lang.AssertionError
	at au.edu.wehi.idsv.debruijn.positional.PathSimplificationIterator.advance(PathSimplificationIterator.java:217)
	at au.edu.wehi.idsv.debruijn.positional.PathSimplificationIterator.ensureBuffer(PathSimplificationIterator.java:171)
	at au.edu.wehi.idsv.debruijn.positional.PathSimplificationIterator.hasNext(PathSimplificationIterator.java:147)
	at com.google.common.collect.Iterators$PeekingImpl.hasNext(Iterators.java:1171)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.nextPosition(NonReferenceContigAssembler.java:302)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.removeMisassembledPartialContig(NonReferenceContigAssembler.java:287)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.ensureCalledContig(NonReferenceContigAssembler.java:227)
	at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.hasNext(NonReferenceContigAssembler.java:176)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.flushIfRequired(PositionalAssembler.java:68)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:108)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:84)
	at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.hasNext(PositionalAssembler.java:54)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:236)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:201)
	at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$15(AssemblyEvidenceSource.java:83)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by alkodsi** [comment]
When adding these chromosomes to the blacklist, gridss still performs assembly on them. At the end, I get the too many open files error (my ulimit is 31000 and 4 worker threads). I think it is related to these chromosomes because there are about 3000 of them.

**Comment by d-cameron** [comment]
Unfortunately, that's due to what looks like a file memory-mapping bug in htsjdk (the SAM/BAM/CRAM parsing library that I'm using). I call close() but memory mapping is not removed so the limit eventually gets hit.
I just managed a GRIDSS WGS run on 34 input files with a ulimit of 63452 using 40 worker threads so it's somewhat strange you hit it with only 4 threads and one input file.

On the upside, just restarting GRIDSS (after deleting the lock directory) will have it pick up where it left off. On the downside, I don't have control over putting in a proper fix.

**Comment by alkodsi** [comment]
I think it is strange too, that's why I am suspecting that including these chromosomes in assembly is the cause (a lot of extra files). Will removing them from the bam file help?

**Comment by d-cameron** [comment]
I found a lead! http://stackoverflow.com/questions/2972986/how-to-unmap-a-file-from-memory-mapped-using-filechannel-in-java
Blacklisting all the alt contigs will results in a whole lot of file handles being opened then immediately closed hence the file handle exhaustion that doesn't happen on large input data sets even when using an order of magnitude more threads.
I'll add some explicit defensive GCs into GRIDSS and see if that improves things.

**Comment by alkodsi** [comment]
will there be a new release soon with this commit?

**Comment by d-cameron** [comment]
I've been going through my backlog of reporting issues and am trying to get as many fixes into the one release as I can. I'll push one out tomorrow.

**Comment by d-cameron** [comment]
I found a file handle leak at the call variants stage. v1.3.4 should be happy with hg38.

**Comment by datakid** [comment]
Is there a jar for 1.3.4?

**Comment by d-cameron** [comment]
There is now. I accidentally published up the release before the file upload was complete.
