### ISSUE TITLE
 Error assembling

### ISSUE THREAD

**Issue by Tjitskedv** [PapenfussLab/gridss#89]
I'm testing Gridss on my data but ran into an error with one of the samples. The other samples executed normally.
I use default setting, without matched sample. Using 4 worker threads
Linux 3.10.0-514.16.1.el7.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_131-b11; Picard version: 1.4.1

This is the error: 

 PositionalAssembler     Error assembling chr19. This should not happen. Please raise an issue at https://github.com/PapenfussLab/gridss/issues. Attempting recovery by resuming ass
embly at chr19:19258341
java.lang.AssertionError
        at au.edu.wehi.idsv.debruijn.positional.SupportNodeIterator.addSupport(SupportNodeIterator.java:132)
        at au.edu.wehi.idsv.debruijn.positional.SupportNodeIterator.process(SupportNodeIterator.java:108)
        at au.edu.wehi.idsv.debruijn.positional.SupportNodeIterator.advance(SupportNodeIterator.java:171)
        at au.edu.wehi.idsv.debruijn.positional.SupportNodeIterator.ensureBuffer(SupportNodeIterator.java:162)
        at au.edu.wehi.idsv.debruijn.positional.SupportNodeIterator.hasNext(SupportNodeIterator.java:143)
        at com.google.common.collect.Iterators$PeekingImpl.hasNext(Iterators.java:1171)
        at au.edu.wehi.idsv.debruijn.positional.AggregateNodeIterator.process(AggregateNodeIterator.java:69)
        at au.edu.wehi.idsv.debruijn.positional.AggregateNodeIterator.ensureBuffer(AggregateNodeIterator.java:53)
        at au.edu.wehi.idsv.debruijn.positional.AggregateNodeIterator.hasNext(AggregateNodeIterator.java:35)
        at com.google.common.collect.Iterators$PeekingImpl.hasNext(Iterators.java:1171)
        at au.edu.wehi.idsv.debruijn.positional.PathNodeIterator.advance(PathNodeIterator.java:181)
        at au.edu.wehi.idsv.debruijn.positional.PathNodeIterator.next(PathNodeIterator.java:233)
        at au.edu.wehi.idsv.debruijn.positional.PathNodeIterator.next(PathNodeIterator.java:24)
        at com.google.common.collect.Iterators$PeekingImpl.peek(Iterators.java:1194)
        at au.edu.wehi.idsv.debruijn.positional.CollapseIterator.loadGraphNodes(CollapseIterator.java:130)
        at au.edu.wehi.idsv.debruijn.positional.CollapseIterator.ensureBuffer(CollapseIterator.java:119)
        at au.edu.wehi.idsv.debruijn.positional.CollapseIterator.hasNext(CollapseIterator.java:89)
        at com.google.common.collect.Iterators$PeekingImpl.hasNext(Iterators.java:1171)
        at au.edu.wehi.idsv.debruijn.positional.PathSimplificationIterator.advance(PathSimplificationIterator.java:214)
        at au.edu.wehi.idsv.debruijn.positional.PathSimplificationIterator.ensureBuffer(PathSimplificationIterator.java:171)
        at au.edu.wehi.idsv.debruijn.positional.PathSimplificationIterator.hasNext(PathSimplificationIterator.java:147)
        at com.google.common.collect.Iterators$PeekingImpl.hasNext(Iterators.java:1171)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.advanceUnderlying(NonReferenceContigAssembler.java:375)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.advanceUnderlying(NonReferenceContigAssembler.java:338)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.ensureCalledContig(NonReferenceContigAssembler.java:255)
        at au.edu.wehi.idsv.debruijn.positional.NonReferenceContigAssembler.hasNext(NonReferenceContigAssembler.java:182)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.flushIfRequired(PositionalAssembler.java:70)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:106)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.ensureAssembler(PositionalAssembler.java:86)
        at au.edu.wehi.idsv.debruijn.positional.PositionalAssembler.hasNext(PositionalAssembler.java:56)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:267)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.assembleChunk(AssemblyEvidenceSource.java:222)
        at au.edu.wehi.idsv.AssemblyEvidenceSource.lambda$assembleBreakends$14(AssemblyEvidenceSource.java:94)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

**Comment by d-cameron** [comment]
Sorry for taking so long to push a new release out with a fix for this.
https://github.com/PapenfussLab/gridss/releases/tag/v1.4.2
