### ISSUE TITLE
CallVariants    Fatal exception thrown by worker thread. htsjdk.samtools.SAMException: Unexpected exception executing [Rscript /tmp/vchebii/script8984088914408500374.R 

### ISSUE THREAD

**Issue by chirrie** [PapenfussLab/gridss#97]
On executing this command,  
java -Xmx31g -cp gridss-1.4.3-jar-with-dependencies.jar gridss.CallVariants REFERENCE_SEQUENCE=capra.fa INPUT=sample.sorted.bam ASSEMBLY=assembly.bam OUTPUT=sample-gridss.vcf.

I get some outfiles  *.metrics

The after that I get the  error below
gridss.analysis.CollectGridssMetrics done. Elapsed time: 89.02 minutes.
Runtime.totalMemory()=1870659584
ERROR   2017-11-09 11:39:05     CallVariants    Fatal exception thrown by worker thread.
htsjdk.samtools.SAMException: Unexpected exception executing [Rscript /tmp/vchebii/script8984088914408500374.R /home/vchebii/goat/sample.sorted.bam.gridss.working/Ibex.sorted.bam.quality_distribution_metrics /home/vchebii/goat/sample.sorted.bam.gridss.working/sample.sorted.bam.quality_distribution.pdf sample.sorted.bam ]
        at htsjdk.samtools.util.ProcessExecutor.execute(ProcessExecutor.java:111)
        at htsjdk.samtools.util.ProcessExecutor.execute(ProcessExecutor.java:87)
        at picard.util.RExecutor.executeFromFile(RExecutor.java:78)
        at picard.util.RExecutor.executeFromClasspath(RExecutor.java:59)
        at picard.analysis.QualityScoreDistribution.finish(QualityScoreDistribution.java:159)
        at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:157)
        at picard.analysis.CollectMultipleMetrics.doWork(CollectMultipleMetrics.java:424)
        at gridss.analysis.CollectGridssMetrics.doWork(CollectGridssMetrics.java:71)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:205)
        at au.edu.wehi.idsv.SAMEvidenceSource.execute(SAMEvidenceSource.java:156)
        at au.edu.wehi.idsv.SAMEvidenceSource.ensureMetrics(SAMEvidenceSource.java:140)
        at gridss.CallVariants$1$1.call(CallVariants.java:53)
        at gridss.CallVariants$1$1.call(CallVariants.java:49)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Cannot run program "Rscript": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
        at java.lang.Runtime.exec(Runtime.java:485)
        at htsjdk.samtools.util.ProcessExecutor.execute(ProcessExecutor.java:102)
        ... 16 more
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method

**Comment by d-cameron** [comment]
As outlined in the README, GRIDSS requires R to be installed, and `Rscript` to be on `PATH`. I've added a check to the example script to print a friendlier error message than that one you got.

Cheers

**Comment by chirrie** [comment]
Thanks. Working fine now
